dictionaries/kobo/dicthtml-de-en.zip: dictionaries/tei/deu-eng.tei
dictionaries/stardict/wikdict-de-en: dictionaries/tei/deu-eng.tei
dictionaries/kobo/dicthtml-de-fr.zip: dictionaries/tei/deu-fra.tei
dictionaries/stardict/wikdict-de-fr: dictionaries/tei/deu-fra.tei
dictionaries/kobo/dicthtml-de-pl.zip: dictionaries/tei/deu-pol.tei
dictionaries/stardict/wikdict-de-pl: dictionaries/tei/deu-pol.tei
dictionaries/kobo/dicthtml-de-sv.zip: dictionaries/tei/deu-swe.tei
dictionaries/stardict/wikdict-de-sv: dictionaries/tei/deu-swe.tei
dictionaries/kobo/dicthtml-de-es.zip: dictionaries/tei/deu-spa.tei
dictionaries/stardict/wikdict-de-es: dictionaries/tei/deu-spa.tei
dictionaries/kobo/dicthtml-de-pt.zip: dictionaries/tei/deu-por.tei
dictionaries/stardict/wikdict-de-pt: dictionaries/tei/deu-por.tei
dictionaries/kobo/dicthtml-de-fi.zip: dictionaries/tei/deu-fin.tei
dictionaries/stardict/wikdict-de-fi: dictionaries/tei/deu-fin.tei
dictionaries/kobo/dicthtml-de-el.zip: dictionaries/tei/deu-ell.tei
dictionaries/stardict/wikdict-de-el: dictionaries/tei/deu-ell.tei
dictionaries/kobo/dicthtml-de-ru.zip: dictionaries/tei/deu-rus.tei
dictionaries/stardict/wikdict-de-ru: dictionaries/tei/deu-rus.tei
dictionaries/kobo/dicthtml-de-tr.zip: dictionaries/tei/deu-tur.tei
dictionaries/stardict/wikdict-de-tr: dictionaries/tei/deu-tur.tei
dictionaries/kobo/dicthtml-de-bg.zip: dictionaries/tei/deu-bul.tei
dictionaries/stardict/wikdict-de-bg: dictionaries/tei/deu-bul.tei
dictionaries/kobo/dicthtml-de-it.zip: dictionaries/tei/deu-ita.tei
dictionaries/stardict/wikdict-de-it: dictionaries/tei/deu-ita.tei
dictionaries/kobo/dicthtml-de-ja.zip: dictionaries/tei/deu-jpn.tei
dictionaries/stardict/wikdict-de-ja: dictionaries/tei/deu-jpn.tei
dictionaries/kobo/dicthtml-de-id.zip: dictionaries/tei/deu-ind.tei
dictionaries/stardict/wikdict-de-id: dictionaries/tei/deu-ind.tei
dictionaries/kobo/dicthtml-de-nl.zip: dictionaries/tei/deu-nld.tei
dictionaries/stardict/wikdict-de-nl: dictionaries/tei/deu-nld.tei
dictionaries/kobo/dicthtml-de-lt.zip: dictionaries/tei/deu-lit.tei
dictionaries/stardict/wikdict-de-lt: dictionaries/tei/deu-lit.tei
dictionaries/kobo/dicthtml-de-la.zip: dictionaries/tei/deu-lat.tei
dictionaries/stardict/wikdict-de-la: dictionaries/tei/deu-lat.tei
dictionaries/kobo/dicthtml-de-mg.zip: dictionaries/tei/deu-mlg.tei
dictionaries/stardict/wikdict-de-mg: dictionaries/tei/deu-mlg.tei
dictionaries/kobo/dicthtml-de-no.zip: dictionaries/tei/deu-nor.tei
dictionaries/stardict/wikdict-de-no: dictionaries/tei/deu-nor.tei
dictionaries/kobo/dicthtml-en-de.zip: dictionaries/tei/eng-deu.tei
dictionaries/stardict/wikdict-en-de: dictionaries/tei/eng-deu.tei
dictionaries/kobo/dicthtml-en-fr.zip: dictionaries/tei/eng-fra.tei
dictionaries/stardict/wikdict-en-fr: dictionaries/tei/eng-fra.tei
dictionaries/kobo/dicthtml-en-pl.zip: dictionaries/tei/eng-pol.tei
dictionaries/stardict/wikdict-en-pl: dictionaries/tei/eng-pol.tei
dictionaries/kobo/dicthtml-en-sv.zip: dictionaries/tei/eng-swe.tei
dictionaries/stardict/wikdict-en-sv: dictionaries/tei/eng-swe.tei
dictionaries/kobo/dicthtml-en-es.zip: dictionaries/tei/eng-spa.tei
dictionaries/stardict/wikdict-en-es: dictionaries/tei/eng-spa.tei
dictionaries/kobo/dicthtml-en-pt.zip: dictionaries/tei/eng-por.tei
dictionaries/stardict/wikdict-en-pt: dictionaries/tei/eng-por.tei
dictionaries/kobo/dicthtml-en-fi.zip: dictionaries/tei/eng-fin.tei
dictionaries/stardict/wikdict-en-fi: dictionaries/tei/eng-fin.tei
dictionaries/kobo/dicthtml-en-el.zip: dictionaries/tei/eng-ell.tei
dictionaries/stardict/wikdict-en-el: dictionaries/tei/eng-ell.tei
dictionaries/kobo/dicthtml-en-ru.zip: dictionaries/tei/eng-rus.tei
dictionaries/stardict/wikdict-en-ru: dictionaries/tei/eng-rus.tei
dictionaries/kobo/dicthtml-en-tr.zip: dictionaries/tei/eng-tur.tei
dictionaries/stardict/wikdict-en-tr: dictionaries/tei/eng-tur.tei
dictionaries/kobo/dicthtml-en-bg.zip: dictionaries/tei/eng-bul.tei
dictionaries/stardict/wikdict-en-bg: dictionaries/tei/eng-bul.tei
dictionaries/kobo/dicthtml-en-it.zip: dictionaries/tei/eng-ita.tei
dictionaries/stardict/wikdict-en-it: dictionaries/tei/eng-ita.tei
dictionaries/kobo/dicthtml-en-ja.zip: dictionaries/tei/eng-jpn.tei
dictionaries/stardict/wikdict-en-ja: dictionaries/tei/eng-jpn.tei
dictionaries/kobo/dicthtml-en-id.zip: dictionaries/tei/eng-ind.tei
dictionaries/stardict/wikdict-en-id: dictionaries/tei/eng-ind.tei
dictionaries/kobo/dicthtml-en-nl.zip: dictionaries/tei/eng-nld.tei
dictionaries/stardict/wikdict-en-nl: dictionaries/tei/eng-nld.tei
dictionaries/kobo/dicthtml-en-lt.zip: dictionaries/tei/eng-lit.tei
dictionaries/stardict/wikdict-en-lt: dictionaries/tei/eng-lit.tei
dictionaries/kobo/dicthtml-en-la.zip: dictionaries/tei/eng-lat.tei
dictionaries/stardict/wikdict-en-la: dictionaries/tei/eng-lat.tei
dictionaries/kobo/dicthtml-en-mg.zip: dictionaries/tei/eng-mlg.tei
dictionaries/stardict/wikdict-en-mg: dictionaries/tei/eng-mlg.tei
dictionaries/kobo/dicthtml-en-no.zip: dictionaries/tei/eng-nor.tei
dictionaries/stardict/wikdict-en-no: dictionaries/tei/eng-nor.tei
dictionaries/kobo/dicthtml-fr-de.zip: dictionaries/tei/fra-deu.tei
dictionaries/stardict/wikdict-fr-de: dictionaries/tei/fra-deu.tei
dictionaries/kobo/dicthtml-fr-en.zip: dictionaries/tei/fra-eng.tei
dictionaries/stardict/wikdict-fr-en: dictionaries/tei/fra-eng.tei
dictionaries/kobo/dicthtml-fr-pl.zip: dictionaries/tei/fra-pol.tei
dictionaries/stardict/wikdict-fr-pl: dictionaries/tei/fra-pol.tei
dictionaries/kobo/dicthtml-fr-sv.zip: dictionaries/tei/fra-swe.tei
dictionaries/stardict/wikdict-fr-sv: dictionaries/tei/fra-swe.tei
dictionaries/kobo/dicthtml-fr-es.zip: dictionaries/tei/fra-spa.tei
dictionaries/stardict/wikdict-fr-es: dictionaries/tei/fra-spa.tei
dictionaries/kobo/dicthtml-fr-pt.zip: dictionaries/tei/fra-por.tei
dictionaries/stardict/wikdict-fr-pt: dictionaries/tei/fra-por.tei
dictionaries/kobo/dicthtml-fr-fi.zip: dictionaries/tei/fra-fin.tei
dictionaries/stardict/wikdict-fr-fi: dictionaries/tei/fra-fin.tei
dictionaries/kobo/dicthtml-fr-el.zip: dictionaries/tei/fra-ell.tei
dictionaries/stardict/wikdict-fr-el: dictionaries/tei/fra-ell.tei
dictionaries/kobo/dicthtml-fr-ru.zip: dictionaries/tei/fra-rus.tei
dictionaries/stardict/wikdict-fr-ru: dictionaries/tei/fra-rus.tei
dictionaries/kobo/dicthtml-fr-tr.zip: dictionaries/tei/fra-tur.tei
dictionaries/stardict/wikdict-fr-tr: dictionaries/tei/fra-tur.tei
dictionaries/kobo/dicthtml-fr-bg.zip: dictionaries/tei/fra-bul.tei
dictionaries/stardict/wikdict-fr-bg: dictionaries/tei/fra-bul.tei
dictionaries/kobo/dicthtml-fr-it.zip: dictionaries/tei/fra-ita.tei
dictionaries/stardict/wikdict-fr-it: dictionaries/tei/fra-ita.tei
dictionaries/kobo/dicthtml-fr-ja.zip: dictionaries/tei/fra-jpn.tei
dictionaries/stardict/wikdict-fr-ja: dictionaries/tei/fra-jpn.tei
dictionaries/kobo/dicthtml-fr-id.zip: dictionaries/tei/fra-ind.tei
dictionaries/stardict/wikdict-fr-id: dictionaries/tei/fra-ind.tei
dictionaries/kobo/dicthtml-fr-nl.zip: dictionaries/tei/fra-nld.tei
dictionaries/stardict/wikdict-fr-nl: dictionaries/tei/fra-nld.tei
dictionaries/kobo/dicthtml-fr-lt.zip: dictionaries/tei/fra-lit.tei
dictionaries/stardict/wikdict-fr-lt: dictionaries/tei/fra-lit.tei
dictionaries/kobo/dicthtml-fr-la.zip: dictionaries/tei/fra-lat.tei
dictionaries/stardict/wikdict-fr-la: dictionaries/tei/fra-lat.tei
dictionaries/kobo/dicthtml-fr-mg.zip: dictionaries/tei/fra-mlg.tei
dictionaries/stardict/wikdict-fr-mg: dictionaries/tei/fra-mlg.tei
dictionaries/kobo/dicthtml-fr-no.zip: dictionaries/tei/fra-nor.tei
dictionaries/stardict/wikdict-fr-no: dictionaries/tei/fra-nor.tei
dictionaries/kobo/dicthtml-pl-de.zip: dictionaries/tei/pol-deu.tei
dictionaries/stardict/wikdict-pl-de: dictionaries/tei/pol-deu.tei
dictionaries/kobo/dicthtml-pl-en.zip: dictionaries/tei/pol-eng.tei
dictionaries/stardict/wikdict-pl-en: dictionaries/tei/pol-eng.tei
dictionaries/kobo/dicthtml-pl-fr.zip: dictionaries/tei/pol-fra.tei
dictionaries/stardict/wikdict-pl-fr: dictionaries/tei/pol-fra.tei
dictionaries/kobo/dicthtml-pl-sv.zip: dictionaries/tei/pol-swe.tei
dictionaries/stardict/wikdict-pl-sv: dictionaries/tei/pol-swe.tei
dictionaries/kobo/dicthtml-pl-es.zip: dictionaries/tei/pol-spa.tei
dictionaries/stardict/wikdict-pl-es: dictionaries/tei/pol-spa.tei
dictionaries/kobo/dicthtml-pl-pt.zip: dictionaries/tei/pol-por.tei
dictionaries/stardict/wikdict-pl-pt: dictionaries/tei/pol-por.tei
dictionaries/kobo/dicthtml-pl-fi.zip: dictionaries/tei/pol-fin.tei
dictionaries/stardict/wikdict-pl-fi: dictionaries/tei/pol-fin.tei
dictionaries/kobo/dicthtml-pl-el.zip: dictionaries/tei/pol-ell.tei
dictionaries/stardict/wikdict-pl-el: dictionaries/tei/pol-ell.tei
dictionaries/kobo/dicthtml-pl-ru.zip: dictionaries/tei/pol-rus.tei
dictionaries/stardict/wikdict-pl-ru: dictionaries/tei/pol-rus.tei
dictionaries/kobo/dicthtml-pl-tr.zip: dictionaries/tei/pol-tur.tei
dictionaries/stardict/wikdict-pl-tr: dictionaries/tei/pol-tur.tei
dictionaries/kobo/dicthtml-pl-bg.zip: dictionaries/tei/pol-bul.tei
dictionaries/stardict/wikdict-pl-bg: dictionaries/tei/pol-bul.tei
dictionaries/kobo/dicthtml-pl-it.zip: dictionaries/tei/pol-ita.tei
dictionaries/stardict/wikdict-pl-it: dictionaries/tei/pol-ita.tei
dictionaries/kobo/dicthtml-pl-ja.zip: dictionaries/tei/pol-jpn.tei
dictionaries/stardict/wikdict-pl-ja: dictionaries/tei/pol-jpn.tei
dictionaries/kobo/dicthtml-pl-id.zip: dictionaries/tei/pol-ind.tei
dictionaries/stardict/wikdict-pl-id: dictionaries/tei/pol-ind.tei
dictionaries/kobo/dicthtml-pl-nl.zip: dictionaries/tei/pol-nld.tei
dictionaries/stardict/wikdict-pl-nl: dictionaries/tei/pol-nld.tei
dictionaries/kobo/dicthtml-pl-lt.zip: dictionaries/tei/pol-lit.tei
dictionaries/stardict/wikdict-pl-lt: dictionaries/tei/pol-lit.tei
dictionaries/kobo/dicthtml-pl-la.zip: dictionaries/tei/pol-lat.tei
dictionaries/stardict/wikdict-pl-la: dictionaries/tei/pol-lat.tei
dictionaries/kobo/dicthtml-pl-mg.zip: dictionaries/tei/pol-mlg.tei
dictionaries/stardict/wikdict-pl-mg: dictionaries/tei/pol-mlg.tei
dictionaries/kobo/dicthtml-pl-no.zip: dictionaries/tei/pol-nor.tei
dictionaries/stardict/wikdict-pl-no: dictionaries/tei/pol-nor.tei
dictionaries/kobo/dicthtml-sv-de.zip: dictionaries/tei/swe-deu.tei
dictionaries/stardict/wikdict-sv-de: dictionaries/tei/swe-deu.tei
dictionaries/kobo/dicthtml-sv-en.zip: dictionaries/tei/swe-eng.tei
dictionaries/stardict/wikdict-sv-en: dictionaries/tei/swe-eng.tei
dictionaries/kobo/dicthtml-sv-fr.zip: dictionaries/tei/swe-fra.tei
dictionaries/stardict/wikdict-sv-fr: dictionaries/tei/swe-fra.tei
dictionaries/kobo/dicthtml-sv-pl.zip: dictionaries/tei/swe-pol.tei
dictionaries/stardict/wikdict-sv-pl: dictionaries/tei/swe-pol.tei
dictionaries/kobo/dicthtml-sv-es.zip: dictionaries/tei/swe-spa.tei
dictionaries/stardict/wikdict-sv-es: dictionaries/tei/swe-spa.tei
dictionaries/kobo/dicthtml-sv-pt.zip: dictionaries/tei/swe-por.tei
dictionaries/stardict/wikdict-sv-pt: dictionaries/tei/swe-por.tei
dictionaries/kobo/dicthtml-sv-fi.zip: dictionaries/tei/swe-fin.tei
dictionaries/stardict/wikdict-sv-fi: dictionaries/tei/swe-fin.tei
dictionaries/kobo/dicthtml-sv-el.zip: dictionaries/tei/swe-ell.tei
dictionaries/stardict/wikdict-sv-el: dictionaries/tei/swe-ell.tei
dictionaries/kobo/dicthtml-sv-ru.zip: dictionaries/tei/swe-rus.tei
dictionaries/stardict/wikdict-sv-ru: dictionaries/tei/swe-rus.tei
dictionaries/kobo/dicthtml-sv-tr.zip: dictionaries/tei/swe-tur.tei
dictionaries/stardict/wikdict-sv-tr: dictionaries/tei/swe-tur.tei
dictionaries/kobo/dicthtml-sv-bg.zip: dictionaries/tei/swe-bul.tei
dictionaries/stardict/wikdict-sv-bg: dictionaries/tei/swe-bul.tei
dictionaries/kobo/dicthtml-sv-it.zip: dictionaries/tei/swe-ita.tei
dictionaries/stardict/wikdict-sv-it: dictionaries/tei/swe-ita.tei
dictionaries/kobo/dicthtml-sv-ja.zip: dictionaries/tei/swe-jpn.tei
dictionaries/stardict/wikdict-sv-ja: dictionaries/tei/swe-jpn.tei
dictionaries/kobo/dicthtml-sv-id.zip: dictionaries/tei/swe-ind.tei
dictionaries/stardict/wikdict-sv-id: dictionaries/tei/swe-ind.tei
dictionaries/kobo/dicthtml-sv-nl.zip: dictionaries/tei/swe-nld.tei
dictionaries/stardict/wikdict-sv-nl: dictionaries/tei/swe-nld.tei
dictionaries/kobo/dicthtml-sv-lt.zip: dictionaries/tei/swe-lit.tei
dictionaries/stardict/wikdict-sv-lt: dictionaries/tei/swe-lit.tei
dictionaries/kobo/dicthtml-sv-la.zip: dictionaries/tei/swe-lat.tei
dictionaries/stardict/wikdict-sv-la: dictionaries/tei/swe-lat.tei
dictionaries/kobo/dicthtml-sv-mg.zip: dictionaries/tei/swe-mlg.tei
dictionaries/stardict/wikdict-sv-mg: dictionaries/tei/swe-mlg.tei
dictionaries/kobo/dicthtml-sv-no.zip: dictionaries/tei/swe-nor.tei
dictionaries/stardict/wikdict-sv-no: dictionaries/tei/swe-nor.tei
dictionaries/kobo/dicthtml-es-de.zip: dictionaries/tei/spa-deu.tei
dictionaries/stardict/wikdict-es-de: dictionaries/tei/spa-deu.tei
dictionaries/kobo/dicthtml-es-en.zip: dictionaries/tei/spa-eng.tei
dictionaries/stardict/wikdict-es-en: dictionaries/tei/spa-eng.tei
dictionaries/kobo/dicthtml-es-fr.zip: dictionaries/tei/spa-fra.tei
dictionaries/stardict/wikdict-es-fr: dictionaries/tei/spa-fra.tei
dictionaries/kobo/dicthtml-es-pl.zip: dictionaries/tei/spa-pol.tei
dictionaries/stardict/wikdict-es-pl: dictionaries/tei/spa-pol.tei
dictionaries/kobo/dicthtml-es-sv.zip: dictionaries/tei/spa-swe.tei
dictionaries/stardict/wikdict-es-sv: dictionaries/tei/spa-swe.tei
dictionaries/kobo/dicthtml-es-pt.zip: dictionaries/tei/spa-por.tei
dictionaries/stardict/wikdict-es-pt: dictionaries/tei/spa-por.tei
dictionaries/kobo/dicthtml-es-fi.zip: dictionaries/tei/spa-fin.tei
dictionaries/stardict/wikdict-es-fi: dictionaries/tei/spa-fin.tei
dictionaries/kobo/dicthtml-es-el.zip: dictionaries/tei/spa-ell.tei
dictionaries/stardict/wikdict-es-el: dictionaries/tei/spa-ell.tei
dictionaries/kobo/dicthtml-es-ru.zip: dictionaries/tei/spa-rus.tei
dictionaries/stardict/wikdict-es-ru: dictionaries/tei/spa-rus.tei
dictionaries/kobo/dicthtml-es-tr.zip: dictionaries/tei/spa-tur.tei
dictionaries/stardict/wikdict-es-tr: dictionaries/tei/spa-tur.tei
dictionaries/kobo/dicthtml-es-bg.zip: dictionaries/tei/spa-bul.tei
dictionaries/stardict/wikdict-es-bg: dictionaries/tei/spa-bul.tei
dictionaries/kobo/dicthtml-es-it.zip: dictionaries/tei/spa-ita.tei
dictionaries/stardict/wikdict-es-it: dictionaries/tei/spa-ita.tei
dictionaries/kobo/dicthtml-es-ja.zip: dictionaries/tei/spa-jpn.tei
dictionaries/stardict/wikdict-es-ja: dictionaries/tei/spa-jpn.tei
dictionaries/kobo/dicthtml-es-id.zip: dictionaries/tei/spa-ind.tei
dictionaries/stardict/wikdict-es-id: dictionaries/tei/spa-ind.tei
dictionaries/kobo/dicthtml-es-nl.zip: dictionaries/tei/spa-nld.tei
dictionaries/stardict/wikdict-es-nl: dictionaries/tei/spa-nld.tei
dictionaries/kobo/dicthtml-es-lt.zip: dictionaries/tei/spa-lit.tei
dictionaries/stardict/wikdict-es-lt: dictionaries/tei/spa-lit.tei
dictionaries/kobo/dicthtml-es-la.zip: dictionaries/tei/spa-lat.tei
dictionaries/stardict/wikdict-es-la: dictionaries/tei/spa-lat.tei
dictionaries/kobo/dicthtml-es-mg.zip: dictionaries/tei/spa-mlg.tei
dictionaries/stardict/wikdict-es-mg: dictionaries/tei/spa-mlg.tei
dictionaries/kobo/dicthtml-es-no.zip: dictionaries/tei/spa-nor.tei
dictionaries/stardict/wikdict-es-no: dictionaries/tei/spa-nor.tei
dictionaries/kobo/dicthtml-pt-de.zip: dictionaries/tei/por-deu.tei
dictionaries/stardict/wikdict-pt-de: dictionaries/tei/por-deu.tei
dictionaries/kobo/dicthtml-pt-en.zip: dictionaries/tei/por-eng.tei
dictionaries/stardict/wikdict-pt-en: dictionaries/tei/por-eng.tei
dictionaries/kobo/dicthtml-pt-fr.zip: dictionaries/tei/por-fra.tei
dictionaries/stardict/wikdict-pt-fr: dictionaries/tei/por-fra.tei
dictionaries/kobo/dicthtml-pt-pl.zip: dictionaries/tei/por-pol.tei
dictionaries/stardict/wikdict-pt-pl: dictionaries/tei/por-pol.tei
dictionaries/kobo/dicthtml-pt-sv.zip: dictionaries/tei/por-swe.tei
dictionaries/stardict/wikdict-pt-sv: dictionaries/tei/por-swe.tei
dictionaries/kobo/dicthtml-pt-es.zip: dictionaries/tei/por-spa.tei
dictionaries/stardict/wikdict-pt-es: dictionaries/tei/por-spa.tei
dictionaries/kobo/dicthtml-pt-fi.zip: dictionaries/tei/por-fin.tei
dictionaries/stardict/wikdict-pt-fi: dictionaries/tei/por-fin.tei
dictionaries/kobo/dicthtml-pt-el.zip: dictionaries/tei/por-ell.tei
dictionaries/stardict/wikdict-pt-el: dictionaries/tei/por-ell.tei
dictionaries/kobo/dicthtml-pt-ru.zip: dictionaries/tei/por-rus.tei
dictionaries/stardict/wikdict-pt-ru: dictionaries/tei/por-rus.tei
dictionaries/kobo/dicthtml-pt-tr.zip: dictionaries/tei/por-tur.tei
dictionaries/stardict/wikdict-pt-tr: dictionaries/tei/por-tur.tei
dictionaries/kobo/dicthtml-pt-bg.zip: dictionaries/tei/por-bul.tei
dictionaries/stardict/wikdict-pt-bg: dictionaries/tei/por-bul.tei
dictionaries/kobo/dicthtml-pt-it.zip: dictionaries/tei/por-ita.tei
dictionaries/stardict/wikdict-pt-it: dictionaries/tei/por-ita.tei
dictionaries/kobo/dicthtml-pt-ja.zip: dictionaries/tei/por-jpn.tei
dictionaries/stardict/wikdict-pt-ja: dictionaries/tei/por-jpn.tei
dictionaries/kobo/dicthtml-pt-id.zip: dictionaries/tei/por-ind.tei
dictionaries/stardict/wikdict-pt-id: dictionaries/tei/por-ind.tei
dictionaries/kobo/dicthtml-pt-nl.zip: dictionaries/tei/por-nld.tei
dictionaries/stardict/wikdict-pt-nl: dictionaries/tei/por-nld.tei
dictionaries/kobo/dicthtml-pt-lt.zip: dictionaries/tei/por-lit.tei
dictionaries/stardict/wikdict-pt-lt: dictionaries/tei/por-lit.tei
dictionaries/kobo/dicthtml-pt-la.zip: dictionaries/tei/por-lat.tei
dictionaries/stardict/wikdict-pt-la: dictionaries/tei/por-lat.tei
dictionaries/kobo/dicthtml-pt-mg.zip: dictionaries/tei/por-mlg.tei
dictionaries/stardict/wikdict-pt-mg: dictionaries/tei/por-mlg.tei
dictionaries/kobo/dicthtml-pt-no.zip: dictionaries/tei/por-nor.tei
dictionaries/stardict/wikdict-pt-no: dictionaries/tei/por-nor.tei
dictionaries/kobo/dicthtml-fi-de.zip: dictionaries/tei/fin-deu.tei
dictionaries/stardict/wikdict-fi-de: dictionaries/tei/fin-deu.tei
dictionaries/kobo/dicthtml-fi-en.zip: dictionaries/tei/fin-eng.tei
dictionaries/stardict/wikdict-fi-en: dictionaries/tei/fin-eng.tei
dictionaries/kobo/dicthtml-fi-fr.zip: dictionaries/tei/fin-fra.tei
dictionaries/stardict/wikdict-fi-fr: dictionaries/tei/fin-fra.tei
dictionaries/kobo/dicthtml-fi-pl.zip: dictionaries/tei/fin-pol.tei
dictionaries/stardict/wikdict-fi-pl: dictionaries/tei/fin-pol.tei
dictionaries/kobo/dicthtml-fi-sv.zip: dictionaries/tei/fin-swe.tei
dictionaries/stardict/wikdict-fi-sv: dictionaries/tei/fin-swe.tei
dictionaries/kobo/dicthtml-fi-es.zip: dictionaries/tei/fin-spa.tei
dictionaries/stardict/wikdict-fi-es: dictionaries/tei/fin-spa.tei
dictionaries/kobo/dicthtml-fi-pt.zip: dictionaries/tei/fin-por.tei
dictionaries/stardict/wikdict-fi-pt: dictionaries/tei/fin-por.tei
dictionaries/kobo/dicthtml-fi-el.zip: dictionaries/tei/fin-ell.tei
dictionaries/stardict/wikdict-fi-el: dictionaries/tei/fin-ell.tei
dictionaries/kobo/dicthtml-fi-ru.zip: dictionaries/tei/fin-rus.tei
dictionaries/stardict/wikdict-fi-ru: dictionaries/tei/fin-rus.tei
dictionaries/kobo/dicthtml-fi-tr.zip: dictionaries/tei/fin-tur.tei
dictionaries/stardict/wikdict-fi-tr: dictionaries/tei/fin-tur.tei
dictionaries/kobo/dicthtml-fi-bg.zip: dictionaries/tei/fin-bul.tei
dictionaries/stardict/wikdict-fi-bg: dictionaries/tei/fin-bul.tei
dictionaries/kobo/dicthtml-fi-it.zip: dictionaries/tei/fin-ita.tei
dictionaries/stardict/wikdict-fi-it: dictionaries/tei/fin-ita.tei
dictionaries/kobo/dicthtml-fi-ja.zip: dictionaries/tei/fin-jpn.tei
dictionaries/stardict/wikdict-fi-ja: dictionaries/tei/fin-jpn.tei
dictionaries/kobo/dicthtml-fi-id.zip: dictionaries/tei/fin-ind.tei
dictionaries/stardict/wikdict-fi-id: dictionaries/tei/fin-ind.tei
dictionaries/kobo/dicthtml-fi-nl.zip: dictionaries/tei/fin-nld.tei
dictionaries/stardict/wikdict-fi-nl: dictionaries/tei/fin-nld.tei
dictionaries/kobo/dicthtml-fi-lt.zip: dictionaries/tei/fin-lit.tei
dictionaries/stardict/wikdict-fi-lt: dictionaries/tei/fin-lit.tei
dictionaries/kobo/dicthtml-fi-la.zip: dictionaries/tei/fin-lat.tei
dictionaries/stardict/wikdict-fi-la: dictionaries/tei/fin-lat.tei
dictionaries/kobo/dicthtml-fi-mg.zip: dictionaries/tei/fin-mlg.tei
dictionaries/stardict/wikdict-fi-mg: dictionaries/tei/fin-mlg.tei
dictionaries/kobo/dicthtml-fi-no.zip: dictionaries/tei/fin-nor.tei
dictionaries/stardict/wikdict-fi-no: dictionaries/tei/fin-nor.tei
dictionaries/kobo/dicthtml-el-de.zip: dictionaries/tei/ell-deu.tei
dictionaries/stardict/wikdict-el-de: dictionaries/tei/ell-deu.tei
dictionaries/kobo/dicthtml-el-en.zip: dictionaries/tei/ell-eng.tei
dictionaries/stardict/wikdict-el-en: dictionaries/tei/ell-eng.tei
dictionaries/kobo/dicthtml-el-fr.zip: dictionaries/tei/ell-fra.tei
dictionaries/stardict/wikdict-el-fr: dictionaries/tei/ell-fra.tei
dictionaries/kobo/dicthtml-el-pl.zip: dictionaries/tei/ell-pol.tei
dictionaries/stardict/wikdict-el-pl: dictionaries/tei/ell-pol.tei
dictionaries/kobo/dicthtml-el-sv.zip: dictionaries/tei/ell-swe.tei
dictionaries/stardict/wikdict-el-sv: dictionaries/tei/ell-swe.tei
dictionaries/kobo/dicthtml-el-es.zip: dictionaries/tei/ell-spa.tei
dictionaries/stardict/wikdict-el-es: dictionaries/tei/ell-spa.tei
dictionaries/kobo/dicthtml-el-pt.zip: dictionaries/tei/ell-por.tei
dictionaries/stardict/wikdict-el-pt: dictionaries/tei/ell-por.tei
dictionaries/kobo/dicthtml-el-fi.zip: dictionaries/tei/ell-fin.tei
dictionaries/stardict/wikdict-el-fi: dictionaries/tei/ell-fin.tei
dictionaries/kobo/dicthtml-el-ru.zip: dictionaries/tei/ell-rus.tei
dictionaries/stardict/wikdict-el-ru: dictionaries/tei/ell-rus.tei
dictionaries/kobo/dicthtml-el-tr.zip: dictionaries/tei/ell-tur.tei
dictionaries/stardict/wikdict-el-tr: dictionaries/tei/ell-tur.tei
dictionaries/kobo/dicthtml-el-bg.zip: dictionaries/tei/ell-bul.tei
dictionaries/stardict/wikdict-el-bg: dictionaries/tei/ell-bul.tei
dictionaries/kobo/dicthtml-el-it.zip: dictionaries/tei/ell-ita.tei
dictionaries/stardict/wikdict-el-it: dictionaries/tei/ell-ita.tei
dictionaries/kobo/dicthtml-el-ja.zip: dictionaries/tei/ell-jpn.tei
dictionaries/stardict/wikdict-el-ja: dictionaries/tei/ell-jpn.tei
dictionaries/kobo/dicthtml-el-id.zip: dictionaries/tei/ell-ind.tei
dictionaries/stardict/wikdict-el-id: dictionaries/tei/ell-ind.tei
dictionaries/kobo/dicthtml-el-nl.zip: dictionaries/tei/ell-nld.tei
dictionaries/stardict/wikdict-el-nl: dictionaries/tei/ell-nld.tei
dictionaries/kobo/dicthtml-el-lt.zip: dictionaries/tei/ell-lit.tei
dictionaries/stardict/wikdict-el-lt: dictionaries/tei/ell-lit.tei
dictionaries/kobo/dicthtml-el-la.zip: dictionaries/tei/ell-lat.tei
dictionaries/stardict/wikdict-el-la: dictionaries/tei/ell-lat.tei
dictionaries/kobo/dicthtml-el-mg.zip: dictionaries/tei/ell-mlg.tei
dictionaries/stardict/wikdict-el-mg: dictionaries/tei/ell-mlg.tei
dictionaries/kobo/dicthtml-el-no.zip: dictionaries/tei/ell-nor.tei
dictionaries/stardict/wikdict-el-no: dictionaries/tei/ell-nor.tei
dictionaries/kobo/dicthtml-ru-de.zip: dictionaries/tei/rus-deu.tei
dictionaries/stardict/wikdict-ru-de: dictionaries/tei/rus-deu.tei
dictionaries/kobo/dicthtml-ru-en.zip: dictionaries/tei/rus-eng.tei
dictionaries/stardict/wikdict-ru-en: dictionaries/tei/rus-eng.tei
dictionaries/kobo/dicthtml-ru-fr.zip: dictionaries/tei/rus-fra.tei
dictionaries/stardict/wikdict-ru-fr: dictionaries/tei/rus-fra.tei
dictionaries/kobo/dicthtml-ru-pl.zip: dictionaries/tei/rus-pol.tei
dictionaries/stardict/wikdict-ru-pl: dictionaries/tei/rus-pol.tei
dictionaries/kobo/dicthtml-ru-sv.zip: dictionaries/tei/rus-swe.tei
dictionaries/stardict/wikdict-ru-sv: dictionaries/tei/rus-swe.tei
dictionaries/kobo/dicthtml-ru-es.zip: dictionaries/tei/rus-spa.tei
dictionaries/stardict/wikdict-ru-es: dictionaries/tei/rus-spa.tei
dictionaries/kobo/dicthtml-ru-pt.zip: dictionaries/tei/rus-por.tei
dictionaries/stardict/wikdict-ru-pt: dictionaries/tei/rus-por.tei
dictionaries/kobo/dicthtml-ru-fi.zip: dictionaries/tei/rus-fin.tei
dictionaries/stardict/wikdict-ru-fi: dictionaries/tei/rus-fin.tei
dictionaries/kobo/dicthtml-ru-el.zip: dictionaries/tei/rus-ell.tei
dictionaries/stardict/wikdict-ru-el: dictionaries/tei/rus-ell.tei
dictionaries/kobo/dicthtml-ru-tr.zip: dictionaries/tei/rus-tur.tei
dictionaries/stardict/wikdict-ru-tr: dictionaries/tei/rus-tur.tei
dictionaries/kobo/dicthtml-ru-bg.zip: dictionaries/tei/rus-bul.tei
dictionaries/stardict/wikdict-ru-bg: dictionaries/tei/rus-bul.tei
dictionaries/kobo/dicthtml-ru-it.zip: dictionaries/tei/rus-ita.tei
dictionaries/stardict/wikdict-ru-it: dictionaries/tei/rus-ita.tei
dictionaries/kobo/dicthtml-ru-ja.zip: dictionaries/tei/rus-jpn.tei
dictionaries/stardict/wikdict-ru-ja: dictionaries/tei/rus-jpn.tei
dictionaries/kobo/dicthtml-ru-id.zip: dictionaries/tei/rus-ind.tei
dictionaries/stardict/wikdict-ru-id: dictionaries/tei/rus-ind.tei
dictionaries/kobo/dicthtml-ru-nl.zip: dictionaries/tei/rus-nld.tei
dictionaries/stardict/wikdict-ru-nl: dictionaries/tei/rus-nld.tei
dictionaries/kobo/dicthtml-ru-lt.zip: dictionaries/tei/rus-lit.tei
dictionaries/stardict/wikdict-ru-lt: dictionaries/tei/rus-lit.tei
dictionaries/kobo/dicthtml-ru-la.zip: dictionaries/tei/rus-lat.tei
dictionaries/stardict/wikdict-ru-la: dictionaries/tei/rus-lat.tei
dictionaries/kobo/dicthtml-ru-mg.zip: dictionaries/tei/rus-mlg.tei
dictionaries/stardict/wikdict-ru-mg: dictionaries/tei/rus-mlg.tei
dictionaries/kobo/dicthtml-ru-no.zip: dictionaries/tei/rus-nor.tei
dictionaries/stardict/wikdict-ru-no: dictionaries/tei/rus-nor.tei
dictionaries/kobo/dicthtml-tr-de.zip: dictionaries/tei/tur-deu.tei
dictionaries/stardict/wikdict-tr-de: dictionaries/tei/tur-deu.tei
dictionaries/kobo/dicthtml-tr-en.zip: dictionaries/tei/tur-eng.tei
dictionaries/stardict/wikdict-tr-en: dictionaries/tei/tur-eng.tei
dictionaries/kobo/dicthtml-tr-fr.zip: dictionaries/tei/tur-fra.tei
dictionaries/stardict/wikdict-tr-fr: dictionaries/tei/tur-fra.tei
dictionaries/kobo/dicthtml-tr-pl.zip: dictionaries/tei/tur-pol.tei
dictionaries/stardict/wikdict-tr-pl: dictionaries/tei/tur-pol.tei
dictionaries/kobo/dicthtml-tr-sv.zip: dictionaries/tei/tur-swe.tei
dictionaries/stardict/wikdict-tr-sv: dictionaries/tei/tur-swe.tei
dictionaries/kobo/dicthtml-tr-es.zip: dictionaries/tei/tur-spa.tei
dictionaries/stardict/wikdict-tr-es: dictionaries/tei/tur-spa.tei
dictionaries/kobo/dicthtml-tr-pt.zip: dictionaries/tei/tur-por.tei
dictionaries/stardict/wikdict-tr-pt: dictionaries/tei/tur-por.tei
dictionaries/kobo/dicthtml-tr-fi.zip: dictionaries/tei/tur-fin.tei
dictionaries/stardict/wikdict-tr-fi: dictionaries/tei/tur-fin.tei
dictionaries/kobo/dicthtml-tr-el.zip: dictionaries/tei/tur-ell.tei
dictionaries/stardict/wikdict-tr-el: dictionaries/tei/tur-ell.tei
dictionaries/kobo/dicthtml-tr-ru.zip: dictionaries/tei/tur-rus.tei
dictionaries/stardict/wikdict-tr-ru: dictionaries/tei/tur-rus.tei
dictionaries/kobo/dicthtml-tr-bg.zip: dictionaries/tei/tur-bul.tei
dictionaries/stardict/wikdict-tr-bg: dictionaries/tei/tur-bul.tei
dictionaries/kobo/dicthtml-tr-it.zip: dictionaries/tei/tur-ita.tei
dictionaries/stardict/wikdict-tr-it: dictionaries/tei/tur-ita.tei
dictionaries/kobo/dicthtml-tr-ja.zip: dictionaries/tei/tur-jpn.tei
dictionaries/stardict/wikdict-tr-ja: dictionaries/tei/tur-jpn.tei
dictionaries/kobo/dicthtml-tr-id.zip: dictionaries/tei/tur-ind.tei
dictionaries/stardict/wikdict-tr-id: dictionaries/tei/tur-ind.tei
dictionaries/kobo/dicthtml-tr-nl.zip: dictionaries/tei/tur-nld.tei
dictionaries/stardict/wikdict-tr-nl: dictionaries/tei/tur-nld.tei
dictionaries/kobo/dicthtml-tr-lt.zip: dictionaries/tei/tur-lit.tei
dictionaries/stardict/wikdict-tr-lt: dictionaries/tei/tur-lit.tei
dictionaries/kobo/dicthtml-tr-la.zip: dictionaries/tei/tur-lat.tei
dictionaries/stardict/wikdict-tr-la: dictionaries/tei/tur-lat.tei
dictionaries/kobo/dicthtml-tr-mg.zip: dictionaries/tei/tur-mlg.tei
dictionaries/stardict/wikdict-tr-mg: dictionaries/tei/tur-mlg.tei
dictionaries/kobo/dicthtml-tr-no.zip: dictionaries/tei/tur-nor.tei
dictionaries/stardict/wikdict-tr-no: dictionaries/tei/tur-nor.tei
dictionaries/kobo/dicthtml-bg-de.zip: dictionaries/tei/bul-deu.tei
dictionaries/stardict/wikdict-bg-de: dictionaries/tei/bul-deu.tei
dictionaries/kobo/dicthtml-bg-en.zip: dictionaries/tei/bul-eng.tei
dictionaries/stardict/wikdict-bg-en: dictionaries/tei/bul-eng.tei
dictionaries/kobo/dicthtml-bg-fr.zip: dictionaries/tei/bul-fra.tei
dictionaries/stardict/wikdict-bg-fr: dictionaries/tei/bul-fra.tei
dictionaries/kobo/dicthtml-bg-pl.zip: dictionaries/tei/bul-pol.tei
dictionaries/stardict/wikdict-bg-pl: dictionaries/tei/bul-pol.tei
dictionaries/kobo/dicthtml-bg-sv.zip: dictionaries/tei/bul-swe.tei
dictionaries/stardict/wikdict-bg-sv: dictionaries/tei/bul-swe.tei
dictionaries/kobo/dicthtml-bg-es.zip: dictionaries/tei/bul-spa.tei
dictionaries/stardict/wikdict-bg-es: dictionaries/tei/bul-spa.tei
dictionaries/kobo/dicthtml-bg-pt.zip: dictionaries/tei/bul-por.tei
dictionaries/stardict/wikdict-bg-pt: dictionaries/tei/bul-por.tei
dictionaries/kobo/dicthtml-bg-fi.zip: dictionaries/tei/bul-fin.tei
dictionaries/stardict/wikdict-bg-fi: dictionaries/tei/bul-fin.tei
dictionaries/kobo/dicthtml-bg-el.zip: dictionaries/tei/bul-ell.tei
dictionaries/stardict/wikdict-bg-el: dictionaries/tei/bul-ell.tei
dictionaries/kobo/dicthtml-bg-ru.zip: dictionaries/tei/bul-rus.tei
dictionaries/stardict/wikdict-bg-ru: dictionaries/tei/bul-rus.tei
dictionaries/kobo/dicthtml-bg-tr.zip: dictionaries/tei/bul-tur.tei
dictionaries/stardict/wikdict-bg-tr: dictionaries/tei/bul-tur.tei
dictionaries/kobo/dicthtml-bg-it.zip: dictionaries/tei/bul-ita.tei
dictionaries/stardict/wikdict-bg-it: dictionaries/tei/bul-ita.tei
dictionaries/kobo/dicthtml-bg-ja.zip: dictionaries/tei/bul-jpn.tei
dictionaries/stardict/wikdict-bg-ja: dictionaries/tei/bul-jpn.tei
dictionaries/kobo/dicthtml-bg-id.zip: dictionaries/tei/bul-ind.tei
dictionaries/stardict/wikdict-bg-id: dictionaries/tei/bul-ind.tei
dictionaries/kobo/dicthtml-bg-nl.zip: dictionaries/tei/bul-nld.tei
dictionaries/stardict/wikdict-bg-nl: dictionaries/tei/bul-nld.tei
dictionaries/kobo/dicthtml-bg-lt.zip: dictionaries/tei/bul-lit.tei
dictionaries/stardict/wikdict-bg-lt: dictionaries/tei/bul-lit.tei
dictionaries/kobo/dicthtml-bg-la.zip: dictionaries/tei/bul-lat.tei
dictionaries/stardict/wikdict-bg-la: dictionaries/tei/bul-lat.tei
dictionaries/kobo/dicthtml-bg-mg.zip: dictionaries/tei/bul-mlg.tei
dictionaries/stardict/wikdict-bg-mg: dictionaries/tei/bul-mlg.tei
dictionaries/kobo/dicthtml-bg-no.zip: dictionaries/tei/bul-nor.tei
dictionaries/stardict/wikdict-bg-no: dictionaries/tei/bul-nor.tei
dictionaries/kobo/dicthtml-it-de.zip: dictionaries/tei/ita-deu.tei
dictionaries/stardict/wikdict-it-de: dictionaries/tei/ita-deu.tei
dictionaries/kobo/dicthtml-it-en.zip: dictionaries/tei/ita-eng.tei
dictionaries/stardict/wikdict-it-en: dictionaries/tei/ita-eng.tei
dictionaries/kobo/dicthtml-it-fr.zip: dictionaries/tei/ita-fra.tei
dictionaries/stardict/wikdict-it-fr: dictionaries/tei/ita-fra.tei
dictionaries/kobo/dicthtml-it-pl.zip: dictionaries/tei/ita-pol.tei
dictionaries/stardict/wikdict-it-pl: dictionaries/tei/ita-pol.tei
dictionaries/kobo/dicthtml-it-sv.zip: dictionaries/tei/ita-swe.tei
dictionaries/stardict/wikdict-it-sv: dictionaries/tei/ita-swe.tei
dictionaries/kobo/dicthtml-it-es.zip: dictionaries/tei/ita-spa.tei
dictionaries/stardict/wikdict-it-es: dictionaries/tei/ita-spa.tei
dictionaries/kobo/dicthtml-it-pt.zip: dictionaries/tei/ita-por.tei
dictionaries/stardict/wikdict-it-pt: dictionaries/tei/ita-por.tei
dictionaries/kobo/dicthtml-it-fi.zip: dictionaries/tei/ita-fin.tei
dictionaries/stardict/wikdict-it-fi: dictionaries/tei/ita-fin.tei
dictionaries/kobo/dicthtml-it-el.zip: dictionaries/tei/ita-ell.tei
dictionaries/stardict/wikdict-it-el: dictionaries/tei/ita-ell.tei
dictionaries/kobo/dicthtml-it-ru.zip: dictionaries/tei/ita-rus.tei
dictionaries/stardict/wikdict-it-ru: dictionaries/tei/ita-rus.tei
dictionaries/kobo/dicthtml-it-tr.zip: dictionaries/tei/ita-tur.tei
dictionaries/stardict/wikdict-it-tr: dictionaries/tei/ita-tur.tei
dictionaries/kobo/dicthtml-it-bg.zip: dictionaries/tei/ita-bul.tei
dictionaries/stardict/wikdict-it-bg: dictionaries/tei/ita-bul.tei
dictionaries/kobo/dicthtml-it-ja.zip: dictionaries/tei/ita-jpn.tei
dictionaries/stardict/wikdict-it-ja: dictionaries/tei/ita-jpn.tei
dictionaries/kobo/dicthtml-it-id.zip: dictionaries/tei/ita-ind.tei
dictionaries/stardict/wikdict-it-id: dictionaries/tei/ita-ind.tei
dictionaries/kobo/dicthtml-it-nl.zip: dictionaries/tei/ita-nld.tei
dictionaries/stardict/wikdict-it-nl: dictionaries/tei/ita-nld.tei
dictionaries/kobo/dicthtml-it-lt.zip: dictionaries/tei/ita-lit.tei
dictionaries/stardict/wikdict-it-lt: dictionaries/tei/ita-lit.tei
dictionaries/kobo/dicthtml-it-la.zip: dictionaries/tei/ita-lat.tei
dictionaries/stardict/wikdict-it-la: dictionaries/tei/ita-lat.tei
dictionaries/kobo/dicthtml-it-mg.zip: dictionaries/tei/ita-mlg.tei
dictionaries/stardict/wikdict-it-mg: dictionaries/tei/ita-mlg.tei
dictionaries/kobo/dicthtml-it-no.zip: dictionaries/tei/ita-nor.tei
dictionaries/stardict/wikdict-it-no: dictionaries/tei/ita-nor.tei
dictionaries/kobo/dicthtml-ja-de.zip: dictionaries/tei/jpn-deu.tei
dictionaries/stardict/wikdict-ja-de: dictionaries/tei/jpn-deu.tei
dictionaries/kobo/dicthtml-ja-en.zip: dictionaries/tei/jpn-eng.tei
dictionaries/stardict/wikdict-ja-en: dictionaries/tei/jpn-eng.tei
dictionaries/kobo/dicthtml-ja-fr.zip: dictionaries/tei/jpn-fra.tei
dictionaries/stardict/wikdict-ja-fr: dictionaries/tei/jpn-fra.tei
dictionaries/kobo/dicthtml-ja-pl.zip: dictionaries/tei/jpn-pol.tei
dictionaries/stardict/wikdict-ja-pl: dictionaries/tei/jpn-pol.tei
dictionaries/kobo/dicthtml-ja-sv.zip: dictionaries/tei/jpn-swe.tei
dictionaries/stardict/wikdict-ja-sv: dictionaries/tei/jpn-swe.tei
dictionaries/kobo/dicthtml-ja-es.zip: dictionaries/tei/jpn-spa.tei
dictionaries/stardict/wikdict-ja-es: dictionaries/tei/jpn-spa.tei
dictionaries/kobo/dicthtml-ja-pt.zip: dictionaries/tei/jpn-por.tei
dictionaries/stardict/wikdict-ja-pt: dictionaries/tei/jpn-por.tei
dictionaries/kobo/dicthtml-ja-fi.zip: dictionaries/tei/jpn-fin.tei
dictionaries/stardict/wikdict-ja-fi: dictionaries/tei/jpn-fin.tei
dictionaries/kobo/dicthtml-ja-el.zip: dictionaries/tei/jpn-ell.tei
dictionaries/stardict/wikdict-ja-el: dictionaries/tei/jpn-ell.tei
dictionaries/kobo/dicthtml-ja-ru.zip: dictionaries/tei/jpn-rus.tei
dictionaries/stardict/wikdict-ja-ru: dictionaries/tei/jpn-rus.tei
dictionaries/kobo/dicthtml-ja-tr.zip: dictionaries/tei/jpn-tur.tei
dictionaries/stardict/wikdict-ja-tr: dictionaries/tei/jpn-tur.tei
dictionaries/kobo/dicthtml-ja-bg.zip: dictionaries/tei/jpn-bul.tei
dictionaries/stardict/wikdict-ja-bg: dictionaries/tei/jpn-bul.tei
dictionaries/kobo/dicthtml-ja-it.zip: dictionaries/tei/jpn-ita.tei
dictionaries/stardict/wikdict-ja-it: dictionaries/tei/jpn-ita.tei
dictionaries/kobo/dicthtml-ja-id.zip: dictionaries/tei/jpn-ind.tei
dictionaries/stardict/wikdict-ja-id: dictionaries/tei/jpn-ind.tei
dictionaries/kobo/dicthtml-ja-nl.zip: dictionaries/tei/jpn-nld.tei
dictionaries/stardict/wikdict-ja-nl: dictionaries/tei/jpn-nld.tei
dictionaries/kobo/dicthtml-ja-lt.zip: dictionaries/tei/jpn-lit.tei
dictionaries/stardict/wikdict-ja-lt: dictionaries/tei/jpn-lit.tei
dictionaries/kobo/dicthtml-ja-la.zip: dictionaries/tei/jpn-lat.tei
dictionaries/stardict/wikdict-ja-la: dictionaries/tei/jpn-lat.tei
dictionaries/kobo/dicthtml-ja-mg.zip: dictionaries/tei/jpn-mlg.tei
dictionaries/stardict/wikdict-ja-mg: dictionaries/tei/jpn-mlg.tei
dictionaries/kobo/dicthtml-ja-no.zip: dictionaries/tei/jpn-nor.tei
dictionaries/stardict/wikdict-ja-no: dictionaries/tei/jpn-nor.tei
dictionaries/kobo/dicthtml-id-de.zip: dictionaries/tei/ind-deu.tei
dictionaries/stardict/wikdict-id-de: dictionaries/tei/ind-deu.tei
dictionaries/kobo/dicthtml-id-en.zip: dictionaries/tei/ind-eng.tei
dictionaries/stardict/wikdict-id-en: dictionaries/tei/ind-eng.tei
dictionaries/kobo/dicthtml-id-fr.zip: dictionaries/tei/ind-fra.tei
dictionaries/stardict/wikdict-id-fr: dictionaries/tei/ind-fra.tei
dictionaries/kobo/dicthtml-id-pl.zip: dictionaries/tei/ind-pol.tei
dictionaries/stardict/wikdict-id-pl: dictionaries/tei/ind-pol.tei
dictionaries/kobo/dicthtml-id-sv.zip: dictionaries/tei/ind-swe.tei
dictionaries/stardict/wikdict-id-sv: dictionaries/tei/ind-swe.tei
dictionaries/kobo/dicthtml-id-es.zip: dictionaries/tei/ind-spa.tei
dictionaries/stardict/wikdict-id-es: dictionaries/tei/ind-spa.tei
dictionaries/kobo/dicthtml-id-pt.zip: dictionaries/tei/ind-por.tei
dictionaries/stardict/wikdict-id-pt: dictionaries/tei/ind-por.tei
dictionaries/kobo/dicthtml-id-fi.zip: dictionaries/tei/ind-fin.tei
dictionaries/stardict/wikdict-id-fi: dictionaries/tei/ind-fin.tei
dictionaries/kobo/dicthtml-id-el.zip: dictionaries/tei/ind-ell.tei
dictionaries/stardict/wikdict-id-el: dictionaries/tei/ind-ell.tei
dictionaries/kobo/dicthtml-id-ru.zip: dictionaries/tei/ind-rus.tei
dictionaries/stardict/wikdict-id-ru: dictionaries/tei/ind-rus.tei
dictionaries/kobo/dicthtml-id-tr.zip: dictionaries/tei/ind-tur.tei
dictionaries/stardict/wikdict-id-tr: dictionaries/tei/ind-tur.tei
dictionaries/kobo/dicthtml-id-bg.zip: dictionaries/tei/ind-bul.tei
dictionaries/stardict/wikdict-id-bg: dictionaries/tei/ind-bul.tei
dictionaries/kobo/dicthtml-id-it.zip: dictionaries/tei/ind-ita.tei
dictionaries/stardict/wikdict-id-it: dictionaries/tei/ind-ita.tei
dictionaries/kobo/dicthtml-id-ja.zip: dictionaries/tei/ind-jpn.tei
dictionaries/stardict/wikdict-id-ja: dictionaries/tei/ind-jpn.tei
dictionaries/kobo/dicthtml-id-nl.zip: dictionaries/tei/ind-nld.tei
dictionaries/stardict/wikdict-id-nl: dictionaries/tei/ind-nld.tei
dictionaries/kobo/dicthtml-id-lt.zip: dictionaries/tei/ind-lit.tei
dictionaries/stardict/wikdict-id-lt: dictionaries/tei/ind-lit.tei
dictionaries/kobo/dicthtml-id-la.zip: dictionaries/tei/ind-lat.tei
dictionaries/stardict/wikdict-id-la: dictionaries/tei/ind-lat.tei
dictionaries/kobo/dicthtml-id-mg.zip: dictionaries/tei/ind-mlg.tei
dictionaries/stardict/wikdict-id-mg: dictionaries/tei/ind-mlg.tei
dictionaries/kobo/dicthtml-id-no.zip: dictionaries/tei/ind-nor.tei
dictionaries/stardict/wikdict-id-no: dictionaries/tei/ind-nor.tei
dictionaries/kobo/dicthtml-nl-de.zip: dictionaries/tei/nld-deu.tei
dictionaries/stardict/wikdict-nl-de: dictionaries/tei/nld-deu.tei
dictionaries/kobo/dicthtml-nl-en.zip: dictionaries/tei/nld-eng.tei
dictionaries/stardict/wikdict-nl-en: dictionaries/tei/nld-eng.tei
dictionaries/kobo/dicthtml-nl-fr.zip: dictionaries/tei/nld-fra.tei
dictionaries/stardict/wikdict-nl-fr: dictionaries/tei/nld-fra.tei
dictionaries/kobo/dicthtml-nl-pl.zip: dictionaries/tei/nld-pol.tei
dictionaries/stardict/wikdict-nl-pl: dictionaries/tei/nld-pol.tei
dictionaries/kobo/dicthtml-nl-sv.zip: dictionaries/tei/nld-swe.tei
dictionaries/stardict/wikdict-nl-sv: dictionaries/tei/nld-swe.tei
dictionaries/kobo/dicthtml-nl-es.zip: dictionaries/tei/nld-spa.tei
dictionaries/stardict/wikdict-nl-es: dictionaries/tei/nld-spa.tei
dictionaries/kobo/dicthtml-nl-pt.zip: dictionaries/tei/nld-por.tei
dictionaries/stardict/wikdict-nl-pt: dictionaries/tei/nld-por.tei
dictionaries/kobo/dicthtml-nl-fi.zip: dictionaries/tei/nld-fin.tei
dictionaries/stardict/wikdict-nl-fi: dictionaries/tei/nld-fin.tei
dictionaries/kobo/dicthtml-nl-el.zip: dictionaries/tei/nld-ell.tei
dictionaries/stardict/wikdict-nl-el: dictionaries/tei/nld-ell.tei
dictionaries/kobo/dicthtml-nl-ru.zip: dictionaries/tei/nld-rus.tei
dictionaries/stardict/wikdict-nl-ru: dictionaries/tei/nld-rus.tei
dictionaries/kobo/dicthtml-nl-tr.zip: dictionaries/tei/nld-tur.tei
dictionaries/stardict/wikdict-nl-tr: dictionaries/tei/nld-tur.tei
dictionaries/kobo/dicthtml-nl-bg.zip: dictionaries/tei/nld-bul.tei
dictionaries/stardict/wikdict-nl-bg: dictionaries/tei/nld-bul.tei
dictionaries/kobo/dicthtml-nl-it.zip: dictionaries/tei/nld-ita.tei
dictionaries/stardict/wikdict-nl-it: dictionaries/tei/nld-ita.tei
dictionaries/kobo/dicthtml-nl-ja.zip: dictionaries/tei/nld-jpn.tei
dictionaries/stardict/wikdict-nl-ja: dictionaries/tei/nld-jpn.tei
dictionaries/kobo/dicthtml-nl-id.zip: dictionaries/tei/nld-ind.tei
dictionaries/stardict/wikdict-nl-id: dictionaries/tei/nld-ind.tei
dictionaries/kobo/dicthtml-nl-lt.zip: dictionaries/tei/nld-lit.tei
dictionaries/stardict/wikdict-nl-lt: dictionaries/tei/nld-lit.tei
dictionaries/kobo/dicthtml-nl-la.zip: dictionaries/tei/nld-lat.tei
dictionaries/stardict/wikdict-nl-la: dictionaries/tei/nld-lat.tei
dictionaries/kobo/dicthtml-nl-mg.zip: dictionaries/tei/nld-mlg.tei
dictionaries/stardict/wikdict-nl-mg: dictionaries/tei/nld-mlg.tei
dictionaries/kobo/dicthtml-nl-no.zip: dictionaries/tei/nld-nor.tei
dictionaries/stardict/wikdict-nl-no: dictionaries/tei/nld-nor.tei
dictionaries/kobo/dicthtml-lt-de.zip: dictionaries/tei/lit-deu.tei
dictionaries/stardict/wikdict-lt-de: dictionaries/tei/lit-deu.tei
dictionaries/kobo/dicthtml-lt-en.zip: dictionaries/tei/lit-eng.tei
dictionaries/stardict/wikdict-lt-en: dictionaries/tei/lit-eng.tei
dictionaries/kobo/dicthtml-lt-fr.zip: dictionaries/tei/lit-fra.tei
dictionaries/stardict/wikdict-lt-fr: dictionaries/tei/lit-fra.tei
dictionaries/kobo/dicthtml-lt-pl.zip: dictionaries/tei/lit-pol.tei
dictionaries/stardict/wikdict-lt-pl: dictionaries/tei/lit-pol.tei
dictionaries/kobo/dicthtml-lt-sv.zip: dictionaries/tei/lit-swe.tei
dictionaries/stardict/wikdict-lt-sv: dictionaries/tei/lit-swe.tei
dictionaries/kobo/dicthtml-lt-es.zip: dictionaries/tei/lit-spa.tei
dictionaries/stardict/wikdict-lt-es: dictionaries/tei/lit-spa.tei
dictionaries/kobo/dicthtml-lt-pt.zip: dictionaries/tei/lit-por.tei
dictionaries/stardict/wikdict-lt-pt: dictionaries/tei/lit-por.tei
dictionaries/kobo/dicthtml-lt-fi.zip: dictionaries/tei/lit-fin.tei
dictionaries/stardict/wikdict-lt-fi: dictionaries/tei/lit-fin.tei
dictionaries/kobo/dicthtml-lt-el.zip: dictionaries/tei/lit-ell.tei
dictionaries/stardict/wikdict-lt-el: dictionaries/tei/lit-ell.tei
dictionaries/kobo/dicthtml-lt-ru.zip: dictionaries/tei/lit-rus.tei
dictionaries/stardict/wikdict-lt-ru: dictionaries/tei/lit-rus.tei
dictionaries/kobo/dicthtml-lt-tr.zip: dictionaries/tei/lit-tur.tei
dictionaries/stardict/wikdict-lt-tr: dictionaries/tei/lit-tur.tei
dictionaries/kobo/dicthtml-lt-bg.zip: dictionaries/tei/lit-bul.tei
dictionaries/stardict/wikdict-lt-bg: dictionaries/tei/lit-bul.tei
dictionaries/kobo/dicthtml-lt-it.zip: dictionaries/tei/lit-ita.tei
dictionaries/stardict/wikdict-lt-it: dictionaries/tei/lit-ita.tei
dictionaries/kobo/dicthtml-lt-ja.zip: dictionaries/tei/lit-jpn.tei
dictionaries/stardict/wikdict-lt-ja: dictionaries/tei/lit-jpn.tei
dictionaries/kobo/dicthtml-lt-id.zip: dictionaries/tei/lit-ind.tei
dictionaries/stardict/wikdict-lt-id: dictionaries/tei/lit-ind.tei
dictionaries/kobo/dicthtml-lt-nl.zip: dictionaries/tei/lit-nld.tei
dictionaries/stardict/wikdict-lt-nl: dictionaries/tei/lit-nld.tei
dictionaries/kobo/dicthtml-lt-la.zip: dictionaries/tei/lit-lat.tei
dictionaries/stardict/wikdict-lt-la: dictionaries/tei/lit-lat.tei
dictionaries/kobo/dicthtml-lt-mg.zip: dictionaries/tei/lit-mlg.tei
dictionaries/stardict/wikdict-lt-mg: dictionaries/tei/lit-mlg.tei
dictionaries/kobo/dicthtml-lt-no.zip: dictionaries/tei/lit-nor.tei
dictionaries/stardict/wikdict-lt-no: dictionaries/tei/lit-nor.tei
dictionaries/kobo/dicthtml-la-de.zip: dictionaries/tei/lat-deu.tei
dictionaries/stardict/wikdict-la-de: dictionaries/tei/lat-deu.tei
dictionaries/kobo/dicthtml-la-en.zip: dictionaries/tei/lat-eng.tei
dictionaries/stardict/wikdict-la-en: dictionaries/tei/lat-eng.tei
dictionaries/kobo/dicthtml-la-fr.zip: dictionaries/tei/lat-fra.tei
dictionaries/stardict/wikdict-la-fr: dictionaries/tei/lat-fra.tei
dictionaries/kobo/dicthtml-la-pl.zip: dictionaries/tei/lat-pol.tei
dictionaries/stardict/wikdict-la-pl: dictionaries/tei/lat-pol.tei
dictionaries/kobo/dicthtml-la-sv.zip: dictionaries/tei/lat-swe.tei
dictionaries/stardict/wikdict-la-sv: dictionaries/tei/lat-swe.tei
dictionaries/kobo/dicthtml-la-es.zip: dictionaries/tei/lat-spa.tei
dictionaries/stardict/wikdict-la-es: dictionaries/tei/lat-spa.tei
dictionaries/kobo/dicthtml-la-pt.zip: dictionaries/tei/lat-por.tei
dictionaries/stardict/wikdict-la-pt: dictionaries/tei/lat-por.tei
dictionaries/kobo/dicthtml-la-fi.zip: dictionaries/tei/lat-fin.tei
dictionaries/stardict/wikdict-la-fi: dictionaries/tei/lat-fin.tei
dictionaries/kobo/dicthtml-la-el.zip: dictionaries/tei/lat-ell.tei
dictionaries/stardict/wikdict-la-el: dictionaries/tei/lat-ell.tei
dictionaries/kobo/dicthtml-la-ru.zip: dictionaries/tei/lat-rus.tei
dictionaries/stardict/wikdict-la-ru: dictionaries/tei/lat-rus.tei
dictionaries/kobo/dicthtml-la-tr.zip: dictionaries/tei/lat-tur.tei
dictionaries/stardict/wikdict-la-tr: dictionaries/tei/lat-tur.tei
dictionaries/kobo/dicthtml-la-bg.zip: dictionaries/tei/lat-bul.tei
dictionaries/stardict/wikdict-la-bg: dictionaries/tei/lat-bul.tei
dictionaries/kobo/dicthtml-la-it.zip: dictionaries/tei/lat-ita.tei
dictionaries/stardict/wikdict-la-it: dictionaries/tei/lat-ita.tei
dictionaries/kobo/dicthtml-la-ja.zip: dictionaries/tei/lat-jpn.tei
dictionaries/stardict/wikdict-la-ja: dictionaries/tei/lat-jpn.tei
dictionaries/kobo/dicthtml-la-id.zip: dictionaries/tei/lat-ind.tei
dictionaries/stardict/wikdict-la-id: dictionaries/tei/lat-ind.tei
dictionaries/kobo/dicthtml-la-nl.zip: dictionaries/tei/lat-nld.tei
dictionaries/stardict/wikdict-la-nl: dictionaries/tei/lat-nld.tei
dictionaries/kobo/dicthtml-la-lt.zip: dictionaries/tei/lat-lit.tei
dictionaries/stardict/wikdict-la-lt: dictionaries/tei/lat-lit.tei
dictionaries/kobo/dicthtml-la-mg.zip: dictionaries/tei/lat-mlg.tei
dictionaries/stardict/wikdict-la-mg: dictionaries/tei/lat-mlg.tei
dictionaries/kobo/dicthtml-la-no.zip: dictionaries/tei/lat-nor.tei
dictionaries/stardict/wikdict-la-no: dictionaries/tei/lat-nor.tei
dictionaries/kobo/dicthtml-mg-de.zip: dictionaries/tei/mlg-deu.tei
dictionaries/stardict/wikdict-mg-de: dictionaries/tei/mlg-deu.tei
dictionaries/kobo/dicthtml-mg-en.zip: dictionaries/tei/mlg-eng.tei
dictionaries/stardict/wikdict-mg-en: dictionaries/tei/mlg-eng.tei
dictionaries/kobo/dicthtml-mg-fr.zip: dictionaries/tei/mlg-fra.tei
dictionaries/stardict/wikdict-mg-fr: dictionaries/tei/mlg-fra.tei
dictionaries/kobo/dicthtml-mg-pl.zip: dictionaries/tei/mlg-pol.tei
dictionaries/stardict/wikdict-mg-pl: dictionaries/tei/mlg-pol.tei
dictionaries/kobo/dicthtml-mg-sv.zip: dictionaries/tei/mlg-swe.tei
dictionaries/stardict/wikdict-mg-sv: dictionaries/tei/mlg-swe.tei
dictionaries/kobo/dicthtml-mg-es.zip: dictionaries/tei/mlg-spa.tei
dictionaries/stardict/wikdict-mg-es: dictionaries/tei/mlg-spa.tei
dictionaries/kobo/dicthtml-mg-pt.zip: dictionaries/tei/mlg-por.tei
dictionaries/stardict/wikdict-mg-pt: dictionaries/tei/mlg-por.tei
dictionaries/kobo/dicthtml-mg-fi.zip: dictionaries/tei/mlg-fin.tei
dictionaries/stardict/wikdict-mg-fi: dictionaries/tei/mlg-fin.tei
dictionaries/kobo/dicthtml-mg-el.zip: dictionaries/tei/mlg-ell.tei
dictionaries/stardict/wikdict-mg-el: dictionaries/tei/mlg-ell.tei
dictionaries/kobo/dicthtml-mg-ru.zip: dictionaries/tei/mlg-rus.tei
dictionaries/stardict/wikdict-mg-ru: dictionaries/tei/mlg-rus.tei
dictionaries/kobo/dicthtml-mg-tr.zip: dictionaries/tei/mlg-tur.tei
dictionaries/stardict/wikdict-mg-tr: dictionaries/tei/mlg-tur.tei
dictionaries/kobo/dicthtml-mg-bg.zip: dictionaries/tei/mlg-bul.tei
dictionaries/stardict/wikdict-mg-bg: dictionaries/tei/mlg-bul.tei
dictionaries/kobo/dicthtml-mg-it.zip: dictionaries/tei/mlg-ita.tei
dictionaries/stardict/wikdict-mg-it: dictionaries/tei/mlg-ita.tei
dictionaries/kobo/dicthtml-mg-ja.zip: dictionaries/tei/mlg-jpn.tei
dictionaries/stardict/wikdict-mg-ja: dictionaries/tei/mlg-jpn.tei
dictionaries/kobo/dicthtml-mg-id.zip: dictionaries/tei/mlg-ind.tei
dictionaries/stardict/wikdict-mg-id: dictionaries/tei/mlg-ind.tei
dictionaries/kobo/dicthtml-mg-nl.zip: dictionaries/tei/mlg-nld.tei
dictionaries/stardict/wikdict-mg-nl: dictionaries/tei/mlg-nld.tei
dictionaries/kobo/dicthtml-mg-lt.zip: dictionaries/tei/mlg-lit.tei
dictionaries/stardict/wikdict-mg-lt: dictionaries/tei/mlg-lit.tei
dictionaries/kobo/dicthtml-mg-la.zip: dictionaries/tei/mlg-lat.tei
dictionaries/stardict/wikdict-mg-la: dictionaries/tei/mlg-lat.tei
dictionaries/kobo/dicthtml-mg-no.zip: dictionaries/tei/mlg-nor.tei
dictionaries/stardict/wikdict-mg-no: dictionaries/tei/mlg-nor.tei
dictionaries/kobo/dicthtml-no-de.zip: dictionaries/tei/nor-deu.tei
dictionaries/stardict/wikdict-no-de: dictionaries/tei/nor-deu.tei
dictionaries/kobo/dicthtml-no-en.zip: dictionaries/tei/nor-eng.tei
dictionaries/stardict/wikdict-no-en: dictionaries/tei/nor-eng.tei
dictionaries/kobo/dicthtml-no-fr.zip: dictionaries/tei/nor-fra.tei
dictionaries/stardict/wikdict-no-fr: dictionaries/tei/nor-fra.tei
dictionaries/kobo/dicthtml-no-pl.zip: dictionaries/tei/nor-pol.tei
dictionaries/stardict/wikdict-no-pl: dictionaries/tei/nor-pol.tei
dictionaries/kobo/dicthtml-no-sv.zip: dictionaries/tei/nor-swe.tei
dictionaries/stardict/wikdict-no-sv: dictionaries/tei/nor-swe.tei
dictionaries/kobo/dicthtml-no-es.zip: dictionaries/tei/nor-spa.tei
dictionaries/stardict/wikdict-no-es: dictionaries/tei/nor-spa.tei
dictionaries/kobo/dicthtml-no-pt.zip: dictionaries/tei/nor-por.tei
dictionaries/stardict/wikdict-no-pt: dictionaries/tei/nor-por.tei
dictionaries/kobo/dicthtml-no-fi.zip: dictionaries/tei/nor-fin.tei
dictionaries/stardict/wikdict-no-fi: dictionaries/tei/nor-fin.tei
dictionaries/kobo/dicthtml-no-el.zip: dictionaries/tei/nor-ell.tei
dictionaries/stardict/wikdict-no-el: dictionaries/tei/nor-ell.tei
dictionaries/kobo/dicthtml-no-ru.zip: dictionaries/tei/nor-rus.tei
dictionaries/stardict/wikdict-no-ru: dictionaries/tei/nor-rus.tei
dictionaries/kobo/dicthtml-no-tr.zip: dictionaries/tei/nor-tur.tei
dictionaries/stardict/wikdict-no-tr: dictionaries/tei/nor-tur.tei
dictionaries/kobo/dicthtml-no-bg.zip: dictionaries/tei/nor-bul.tei
dictionaries/stardict/wikdict-no-bg: dictionaries/tei/nor-bul.tei
dictionaries/kobo/dicthtml-no-it.zip: dictionaries/tei/nor-ita.tei
dictionaries/stardict/wikdict-no-it: dictionaries/tei/nor-ita.tei
dictionaries/kobo/dicthtml-no-ja.zip: dictionaries/tei/nor-jpn.tei
dictionaries/stardict/wikdict-no-ja: dictionaries/tei/nor-jpn.tei
dictionaries/kobo/dicthtml-no-id.zip: dictionaries/tei/nor-ind.tei
dictionaries/stardict/wikdict-no-id: dictionaries/tei/nor-ind.tei
dictionaries/kobo/dicthtml-no-nl.zip: dictionaries/tei/nor-nld.tei
dictionaries/stardict/wikdict-no-nl: dictionaries/tei/nor-nld.tei
dictionaries/kobo/dicthtml-no-lt.zip: dictionaries/tei/nor-lit.tei
dictionaries/stardict/wikdict-no-lt: dictionaries/tei/nor-lit.tei
dictionaries/kobo/dicthtml-no-la.zip: dictionaries/tei/nor-lat.tei
dictionaries/stardict/wikdict-no-la: dictionaries/tei/nor-lat.tei
dictionaries/kobo/dicthtml-no-mg.zip: dictionaries/tei/nor-mlg.tei
dictionaries/stardict/wikdict-no-mg: dictionaries/tei/nor-mlg.tei
