dictionaries/kobo/dicthtml-bg-ca.zip: dictionaries/tei/bul-cat.tei
dictionaries/stardict/wikdict-bg-ca: dictionaries/tei/bul-cat.tei
dictionaries/kobo/dicthtml-bg-de.zip: dictionaries/tei/bul-deu.tei
dictionaries/stardict/wikdict-bg-de: dictionaries/tei/bul-deu.tei
dictionaries/kobo/dicthtml-bg-el.zip: dictionaries/tei/bul-ell.tei
dictionaries/stardict/wikdict-bg-el: dictionaries/tei/bul-ell.tei
dictionaries/kobo/dicthtml-bg-en.zip: dictionaries/tei/bul-eng.tei
dictionaries/stardict/wikdict-bg-en: dictionaries/tei/bul-eng.tei
dictionaries/kobo/dicthtml-bg-es.zip: dictionaries/tei/bul-spa.tei
dictionaries/stardict/wikdict-bg-es: dictionaries/tei/bul-spa.tei
dictionaries/kobo/dicthtml-bg-fi.zip: dictionaries/tei/bul-fin.tei
dictionaries/stardict/wikdict-bg-fi: dictionaries/tei/bul-fin.tei
dictionaries/kobo/dicthtml-bg-fr.zip: dictionaries/tei/bul-fra.tei
dictionaries/stardict/wikdict-bg-fr: dictionaries/tei/bul-fra.tei
dictionaries/kobo/dicthtml-bg-ga.zip: dictionaries/tei/bul-gle.tei
dictionaries/stardict/wikdict-bg-ga: dictionaries/tei/bul-gle.tei
dictionaries/kobo/dicthtml-bg-id.zip: dictionaries/tei/bul-ind.tei
dictionaries/stardict/wikdict-bg-id: dictionaries/tei/bul-ind.tei
dictionaries/kobo/dicthtml-bg-it.zip: dictionaries/tei/bul-ita.tei
dictionaries/stardict/wikdict-bg-it: dictionaries/tei/bul-ita.tei
dictionaries/kobo/dicthtml-bg-ja.zip: dictionaries/tei/bul-jpn.tei
dictionaries/stardict/wikdict-bg-ja: dictionaries/tei/bul-jpn.tei
dictionaries/kobo/dicthtml-bg-ku.zip: dictionaries/tei/bul-kur.tei
dictionaries/stardict/wikdict-bg-ku: dictionaries/tei/bul-kur.tei
dictionaries/kobo/dicthtml-bg-la.zip: dictionaries/tei/bul-lat.tei
dictionaries/stardict/wikdict-bg-la: dictionaries/tei/bul-lat.tei
dictionaries/kobo/dicthtml-bg-lt.zip: dictionaries/tei/bul-lit.tei
dictionaries/stardict/wikdict-bg-lt: dictionaries/tei/bul-lit.tei
dictionaries/kobo/dicthtml-bg-mg.zip: dictionaries/tei/bul-mlg.tei
dictionaries/stardict/wikdict-bg-mg: dictionaries/tei/bul-mlg.tei
dictionaries/kobo/dicthtml-bg-nl.zip: dictionaries/tei/bul-nld.tei
dictionaries/stardict/wikdict-bg-nl: dictionaries/tei/bul-nld.tei
dictionaries/kobo/dicthtml-bg-no.zip: dictionaries/tei/bul-nor.tei
dictionaries/stardict/wikdict-bg-no: dictionaries/tei/bul-nor.tei
dictionaries/kobo/dicthtml-bg-pl.zip: dictionaries/tei/bul-pol.tei
dictionaries/stardict/wikdict-bg-pl: dictionaries/tei/bul-pol.tei
dictionaries/kobo/dicthtml-bg-pt.zip: dictionaries/tei/bul-por.tei
dictionaries/stardict/wikdict-bg-pt: dictionaries/tei/bul-por.tei
dictionaries/kobo/dicthtml-bg-ru.zip: dictionaries/tei/bul-rus.tei
dictionaries/stardict/wikdict-bg-ru: dictionaries/tei/bul-rus.tei
dictionaries/kobo/dicthtml-bg-sv.zip: dictionaries/tei/bul-swe.tei
dictionaries/stardict/wikdict-bg-sv: dictionaries/tei/bul-swe.tei
dictionaries/kobo/dicthtml-bg-tr.zip: dictionaries/tei/bul-tur.tei
dictionaries/stardict/wikdict-bg-tr: dictionaries/tei/bul-tur.tei
dictionaries/kobo/dicthtml-bg-zh.zip: dictionaries/tei/bul-zho.tei
dictionaries/stardict/wikdict-bg-zh: dictionaries/tei/bul-zho.tei
dictionaries/kobo/dicthtml-ca-bg.zip: dictionaries/tei/cat-bul.tei
dictionaries/stardict/wikdict-ca-bg: dictionaries/tei/cat-bul.tei
dictionaries/kobo/dicthtml-ca-de.zip: dictionaries/tei/cat-deu.tei
dictionaries/stardict/wikdict-ca-de: dictionaries/tei/cat-deu.tei
dictionaries/kobo/dicthtml-ca-el.zip: dictionaries/tei/cat-ell.tei
dictionaries/stardict/wikdict-ca-el: dictionaries/tei/cat-ell.tei
dictionaries/kobo/dicthtml-ca-en.zip: dictionaries/tei/cat-eng.tei
dictionaries/stardict/wikdict-ca-en: dictionaries/tei/cat-eng.tei
dictionaries/kobo/dicthtml-ca-es.zip: dictionaries/tei/cat-spa.tei
dictionaries/stardict/wikdict-ca-es: dictionaries/tei/cat-spa.tei
dictionaries/kobo/dicthtml-ca-fi.zip: dictionaries/tei/cat-fin.tei
dictionaries/stardict/wikdict-ca-fi: dictionaries/tei/cat-fin.tei
dictionaries/kobo/dicthtml-ca-fr.zip: dictionaries/tei/cat-fra.tei
dictionaries/stardict/wikdict-ca-fr: dictionaries/tei/cat-fra.tei
dictionaries/kobo/dicthtml-ca-ga.zip: dictionaries/tei/cat-gle.tei
dictionaries/stardict/wikdict-ca-ga: dictionaries/tei/cat-gle.tei
dictionaries/kobo/dicthtml-ca-id.zip: dictionaries/tei/cat-ind.tei
dictionaries/stardict/wikdict-ca-id: dictionaries/tei/cat-ind.tei
dictionaries/kobo/dicthtml-ca-it.zip: dictionaries/tei/cat-ita.tei
dictionaries/stardict/wikdict-ca-it: dictionaries/tei/cat-ita.tei
dictionaries/kobo/dicthtml-ca-ja.zip: dictionaries/tei/cat-jpn.tei
dictionaries/stardict/wikdict-ca-ja: dictionaries/tei/cat-jpn.tei
dictionaries/kobo/dicthtml-ca-ku.zip: dictionaries/tei/cat-kur.tei
dictionaries/stardict/wikdict-ca-ku: dictionaries/tei/cat-kur.tei
dictionaries/kobo/dicthtml-ca-la.zip: dictionaries/tei/cat-lat.tei
dictionaries/stardict/wikdict-ca-la: dictionaries/tei/cat-lat.tei
dictionaries/kobo/dicthtml-ca-lt.zip: dictionaries/tei/cat-lit.tei
dictionaries/stardict/wikdict-ca-lt: dictionaries/tei/cat-lit.tei
dictionaries/kobo/dicthtml-ca-mg.zip: dictionaries/tei/cat-mlg.tei
dictionaries/stardict/wikdict-ca-mg: dictionaries/tei/cat-mlg.tei
dictionaries/kobo/dicthtml-ca-nl.zip: dictionaries/tei/cat-nld.tei
dictionaries/stardict/wikdict-ca-nl: dictionaries/tei/cat-nld.tei
dictionaries/kobo/dicthtml-ca-no.zip: dictionaries/tei/cat-nor.tei
dictionaries/stardict/wikdict-ca-no: dictionaries/tei/cat-nor.tei
dictionaries/kobo/dicthtml-ca-pl.zip: dictionaries/tei/cat-pol.tei
dictionaries/stardict/wikdict-ca-pl: dictionaries/tei/cat-pol.tei
dictionaries/kobo/dicthtml-ca-pt.zip: dictionaries/tei/cat-por.tei
dictionaries/stardict/wikdict-ca-pt: dictionaries/tei/cat-por.tei
dictionaries/kobo/dicthtml-ca-ru.zip: dictionaries/tei/cat-rus.tei
dictionaries/stardict/wikdict-ca-ru: dictionaries/tei/cat-rus.tei
dictionaries/kobo/dicthtml-ca-sv.zip: dictionaries/tei/cat-swe.tei
dictionaries/stardict/wikdict-ca-sv: dictionaries/tei/cat-swe.tei
dictionaries/kobo/dicthtml-ca-tr.zip: dictionaries/tei/cat-tur.tei
dictionaries/stardict/wikdict-ca-tr: dictionaries/tei/cat-tur.tei
dictionaries/kobo/dicthtml-ca-zh.zip: dictionaries/tei/cat-zho.tei
dictionaries/stardict/wikdict-ca-zh: dictionaries/tei/cat-zho.tei
dictionaries/kobo/dicthtml-de-bg.zip: dictionaries/tei/deu-bul.tei
dictionaries/stardict/wikdict-de-bg: dictionaries/tei/deu-bul.tei
dictionaries/kobo/dicthtml-de-ca.zip: dictionaries/tei/deu-cat.tei
dictionaries/stardict/wikdict-de-ca: dictionaries/tei/deu-cat.tei
dictionaries/kobo/dicthtml-de-el.zip: dictionaries/tei/deu-ell.tei
dictionaries/stardict/wikdict-de-el: dictionaries/tei/deu-ell.tei
dictionaries/kobo/dicthtml-de-en.zip: dictionaries/tei/deu-eng.tei
dictionaries/stardict/wikdict-de-en: dictionaries/tei/deu-eng.tei
dictionaries/kobo/dicthtml-de-es.zip: dictionaries/tei/deu-spa.tei
dictionaries/stardict/wikdict-de-es: dictionaries/tei/deu-spa.tei
dictionaries/kobo/dicthtml-de-fi.zip: dictionaries/tei/deu-fin.tei
dictionaries/stardict/wikdict-de-fi: dictionaries/tei/deu-fin.tei
dictionaries/kobo/dicthtml-de-fr.zip: dictionaries/tei/deu-fra.tei
dictionaries/stardict/wikdict-de-fr: dictionaries/tei/deu-fra.tei
dictionaries/kobo/dicthtml-de-ga.zip: dictionaries/tei/deu-gle.tei
dictionaries/stardict/wikdict-de-ga: dictionaries/tei/deu-gle.tei
dictionaries/kobo/dicthtml-de-id.zip: dictionaries/tei/deu-ind.tei
dictionaries/stardict/wikdict-de-id: dictionaries/tei/deu-ind.tei
dictionaries/kobo/dicthtml-de-it.zip: dictionaries/tei/deu-ita.tei
dictionaries/stardict/wikdict-de-it: dictionaries/tei/deu-ita.tei
dictionaries/kobo/dicthtml-de-ja.zip: dictionaries/tei/deu-jpn.tei
dictionaries/stardict/wikdict-de-ja: dictionaries/tei/deu-jpn.tei
dictionaries/kobo/dicthtml-de-ku.zip: dictionaries/tei/deu-kur.tei
dictionaries/stardict/wikdict-de-ku: dictionaries/tei/deu-kur.tei
dictionaries/kobo/dicthtml-de-la.zip: dictionaries/tei/deu-lat.tei
dictionaries/stardict/wikdict-de-la: dictionaries/tei/deu-lat.tei
dictionaries/kobo/dicthtml-de-lt.zip: dictionaries/tei/deu-lit.tei
dictionaries/stardict/wikdict-de-lt: dictionaries/tei/deu-lit.tei
dictionaries/kobo/dicthtml-de-mg.zip: dictionaries/tei/deu-mlg.tei
dictionaries/stardict/wikdict-de-mg: dictionaries/tei/deu-mlg.tei
dictionaries/kobo/dicthtml-de-nl.zip: dictionaries/tei/deu-nld.tei
dictionaries/stardict/wikdict-de-nl: dictionaries/tei/deu-nld.tei
dictionaries/kobo/dicthtml-de-no.zip: dictionaries/tei/deu-nor.tei
dictionaries/stardict/wikdict-de-no: dictionaries/tei/deu-nor.tei
dictionaries/kobo/dicthtml-de-pl.zip: dictionaries/tei/deu-pol.tei
dictionaries/stardict/wikdict-de-pl: dictionaries/tei/deu-pol.tei
dictionaries/kobo/dicthtml-de-pt.zip: dictionaries/tei/deu-por.tei
dictionaries/stardict/wikdict-de-pt: dictionaries/tei/deu-por.tei
dictionaries/kobo/dicthtml-de-ru.zip: dictionaries/tei/deu-rus.tei
dictionaries/stardict/wikdict-de-ru: dictionaries/tei/deu-rus.tei
dictionaries/kobo/dicthtml-de-sv.zip: dictionaries/tei/deu-swe.tei
dictionaries/stardict/wikdict-de-sv: dictionaries/tei/deu-swe.tei
dictionaries/kobo/dicthtml-de-tr.zip: dictionaries/tei/deu-tur.tei
dictionaries/stardict/wikdict-de-tr: dictionaries/tei/deu-tur.tei
dictionaries/kobo/dicthtml-de-zh.zip: dictionaries/tei/deu-zho.tei
dictionaries/stardict/wikdict-de-zh: dictionaries/tei/deu-zho.tei
dictionaries/kobo/dicthtml-el-bg.zip: dictionaries/tei/ell-bul.tei
dictionaries/stardict/wikdict-el-bg: dictionaries/tei/ell-bul.tei
dictionaries/kobo/dicthtml-el-ca.zip: dictionaries/tei/ell-cat.tei
dictionaries/stardict/wikdict-el-ca: dictionaries/tei/ell-cat.tei
dictionaries/kobo/dicthtml-el-de.zip: dictionaries/tei/ell-deu.tei
dictionaries/stardict/wikdict-el-de: dictionaries/tei/ell-deu.tei
dictionaries/kobo/dicthtml-el-en.zip: dictionaries/tei/ell-eng.tei
dictionaries/stardict/wikdict-el-en: dictionaries/tei/ell-eng.tei
dictionaries/kobo/dicthtml-el-es.zip: dictionaries/tei/ell-spa.tei
dictionaries/stardict/wikdict-el-es: dictionaries/tei/ell-spa.tei
dictionaries/kobo/dicthtml-el-fi.zip: dictionaries/tei/ell-fin.tei
dictionaries/stardict/wikdict-el-fi: dictionaries/tei/ell-fin.tei
dictionaries/kobo/dicthtml-el-fr.zip: dictionaries/tei/ell-fra.tei
dictionaries/stardict/wikdict-el-fr: dictionaries/tei/ell-fra.tei
dictionaries/kobo/dicthtml-el-ga.zip: dictionaries/tei/ell-gle.tei
dictionaries/stardict/wikdict-el-ga: dictionaries/tei/ell-gle.tei
dictionaries/kobo/dicthtml-el-id.zip: dictionaries/tei/ell-ind.tei
dictionaries/stardict/wikdict-el-id: dictionaries/tei/ell-ind.tei
dictionaries/kobo/dicthtml-el-it.zip: dictionaries/tei/ell-ita.tei
dictionaries/stardict/wikdict-el-it: dictionaries/tei/ell-ita.tei
dictionaries/kobo/dicthtml-el-ja.zip: dictionaries/tei/ell-jpn.tei
dictionaries/stardict/wikdict-el-ja: dictionaries/tei/ell-jpn.tei
dictionaries/kobo/dicthtml-el-ku.zip: dictionaries/tei/ell-kur.tei
dictionaries/stardict/wikdict-el-ku: dictionaries/tei/ell-kur.tei
dictionaries/kobo/dicthtml-el-la.zip: dictionaries/tei/ell-lat.tei
dictionaries/stardict/wikdict-el-la: dictionaries/tei/ell-lat.tei
dictionaries/kobo/dicthtml-el-lt.zip: dictionaries/tei/ell-lit.tei
dictionaries/stardict/wikdict-el-lt: dictionaries/tei/ell-lit.tei
dictionaries/kobo/dicthtml-el-mg.zip: dictionaries/tei/ell-mlg.tei
dictionaries/stardict/wikdict-el-mg: dictionaries/tei/ell-mlg.tei
dictionaries/kobo/dicthtml-el-nl.zip: dictionaries/tei/ell-nld.tei
dictionaries/stardict/wikdict-el-nl: dictionaries/tei/ell-nld.tei
dictionaries/kobo/dicthtml-el-no.zip: dictionaries/tei/ell-nor.tei
dictionaries/stardict/wikdict-el-no: dictionaries/tei/ell-nor.tei
dictionaries/kobo/dicthtml-el-pl.zip: dictionaries/tei/ell-pol.tei
dictionaries/stardict/wikdict-el-pl: dictionaries/tei/ell-pol.tei
dictionaries/kobo/dicthtml-el-pt.zip: dictionaries/tei/ell-por.tei
dictionaries/stardict/wikdict-el-pt: dictionaries/tei/ell-por.tei
dictionaries/kobo/dicthtml-el-ru.zip: dictionaries/tei/ell-rus.tei
dictionaries/stardict/wikdict-el-ru: dictionaries/tei/ell-rus.tei
dictionaries/kobo/dicthtml-el-sv.zip: dictionaries/tei/ell-swe.tei
dictionaries/stardict/wikdict-el-sv: dictionaries/tei/ell-swe.tei
dictionaries/kobo/dicthtml-el-tr.zip: dictionaries/tei/ell-tur.tei
dictionaries/stardict/wikdict-el-tr: dictionaries/tei/ell-tur.tei
dictionaries/kobo/dicthtml-el-zh.zip: dictionaries/tei/ell-zho.tei
dictionaries/stardict/wikdict-el-zh: dictionaries/tei/ell-zho.tei
dictionaries/kobo/dicthtml-en-bg.zip: dictionaries/tei/eng-bul.tei
dictionaries/stardict/wikdict-en-bg: dictionaries/tei/eng-bul.tei
dictionaries/kobo/dicthtml-en-ca.zip: dictionaries/tei/eng-cat.tei
dictionaries/stardict/wikdict-en-ca: dictionaries/tei/eng-cat.tei
dictionaries/kobo/dicthtml-en-de.zip: dictionaries/tei/eng-deu.tei
dictionaries/stardict/wikdict-en-de: dictionaries/tei/eng-deu.tei
dictionaries/kobo/dicthtml-en-el.zip: dictionaries/tei/eng-ell.tei
dictionaries/stardict/wikdict-en-el: dictionaries/tei/eng-ell.tei
dictionaries/kobo/dicthtml-en-es.zip: dictionaries/tei/eng-spa.tei
dictionaries/stardict/wikdict-en-es: dictionaries/tei/eng-spa.tei
dictionaries/kobo/dicthtml-en-fi.zip: dictionaries/tei/eng-fin.tei
dictionaries/stardict/wikdict-en-fi: dictionaries/tei/eng-fin.tei
dictionaries/kobo/dicthtml-en-fr.zip: dictionaries/tei/eng-fra.tei
dictionaries/stardict/wikdict-en-fr: dictionaries/tei/eng-fra.tei
dictionaries/kobo/dicthtml-en-ga.zip: dictionaries/tei/eng-gle.tei
dictionaries/stardict/wikdict-en-ga: dictionaries/tei/eng-gle.tei
dictionaries/kobo/dicthtml-en-id.zip: dictionaries/tei/eng-ind.tei
dictionaries/stardict/wikdict-en-id: dictionaries/tei/eng-ind.tei
dictionaries/kobo/dicthtml-en-it.zip: dictionaries/tei/eng-ita.tei
dictionaries/stardict/wikdict-en-it: dictionaries/tei/eng-ita.tei
dictionaries/kobo/dicthtml-en-ja.zip: dictionaries/tei/eng-jpn.tei
dictionaries/stardict/wikdict-en-ja: dictionaries/tei/eng-jpn.tei
dictionaries/kobo/dicthtml-en-ku.zip: dictionaries/tei/eng-kur.tei
dictionaries/stardict/wikdict-en-ku: dictionaries/tei/eng-kur.tei
dictionaries/kobo/dicthtml-en-la.zip: dictionaries/tei/eng-lat.tei
dictionaries/stardict/wikdict-en-la: dictionaries/tei/eng-lat.tei
dictionaries/kobo/dicthtml-en-lt.zip: dictionaries/tei/eng-lit.tei
dictionaries/stardict/wikdict-en-lt: dictionaries/tei/eng-lit.tei
dictionaries/kobo/dicthtml-en-mg.zip: dictionaries/tei/eng-mlg.tei
dictionaries/stardict/wikdict-en-mg: dictionaries/tei/eng-mlg.tei
dictionaries/kobo/dicthtml-en-nl.zip: dictionaries/tei/eng-nld.tei
dictionaries/stardict/wikdict-en-nl: dictionaries/tei/eng-nld.tei
dictionaries/kobo/dicthtml-en-no.zip: dictionaries/tei/eng-nor.tei
dictionaries/stardict/wikdict-en-no: dictionaries/tei/eng-nor.tei
dictionaries/kobo/dicthtml-en-pl.zip: dictionaries/tei/eng-pol.tei
dictionaries/stardict/wikdict-en-pl: dictionaries/tei/eng-pol.tei
dictionaries/kobo/dicthtml-en-pt.zip: dictionaries/tei/eng-por.tei
dictionaries/stardict/wikdict-en-pt: dictionaries/tei/eng-por.tei
dictionaries/kobo/dicthtml-en-ru.zip: dictionaries/tei/eng-rus.tei
dictionaries/stardict/wikdict-en-ru: dictionaries/tei/eng-rus.tei
dictionaries/kobo/dicthtml-en-sv.zip: dictionaries/tei/eng-swe.tei
dictionaries/stardict/wikdict-en-sv: dictionaries/tei/eng-swe.tei
dictionaries/kobo/dicthtml-en-tr.zip: dictionaries/tei/eng-tur.tei
dictionaries/stardict/wikdict-en-tr: dictionaries/tei/eng-tur.tei
dictionaries/kobo/dicthtml-en-zh.zip: dictionaries/tei/eng-zho.tei
dictionaries/stardict/wikdict-en-zh: dictionaries/tei/eng-zho.tei
dictionaries/kobo/dicthtml-es-bg.zip: dictionaries/tei/spa-bul.tei
dictionaries/stardict/wikdict-es-bg: dictionaries/tei/spa-bul.tei
dictionaries/kobo/dicthtml-es-ca.zip: dictionaries/tei/spa-cat.tei
dictionaries/stardict/wikdict-es-ca: dictionaries/tei/spa-cat.tei
dictionaries/kobo/dicthtml-es-de.zip: dictionaries/tei/spa-deu.tei
dictionaries/stardict/wikdict-es-de: dictionaries/tei/spa-deu.tei
dictionaries/kobo/dicthtml-es-el.zip: dictionaries/tei/spa-ell.tei
dictionaries/stardict/wikdict-es-el: dictionaries/tei/spa-ell.tei
dictionaries/kobo/dicthtml-es-en.zip: dictionaries/tei/spa-eng.tei
dictionaries/stardict/wikdict-es-en: dictionaries/tei/spa-eng.tei
dictionaries/kobo/dicthtml-es-fi.zip: dictionaries/tei/spa-fin.tei
dictionaries/stardict/wikdict-es-fi: dictionaries/tei/spa-fin.tei
dictionaries/kobo/dicthtml-es-fr.zip: dictionaries/tei/spa-fra.tei
dictionaries/stardict/wikdict-es-fr: dictionaries/tei/spa-fra.tei
dictionaries/kobo/dicthtml-es-ga.zip: dictionaries/tei/spa-gle.tei
dictionaries/stardict/wikdict-es-ga: dictionaries/tei/spa-gle.tei
dictionaries/kobo/dicthtml-es-id.zip: dictionaries/tei/spa-ind.tei
dictionaries/stardict/wikdict-es-id: dictionaries/tei/spa-ind.tei
dictionaries/kobo/dicthtml-es-it.zip: dictionaries/tei/spa-ita.tei
dictionaries/stardict/wikdict-es-it: dictionaries/tei/spa-ita.tei
dictionaries/kobo/dicthtml-es-ja.zip: dictionaries/tei/spa-jpn.tei
dictionaries/stardict/wikdict-es-ja: dictionaries/tei/spa-jpn.tei
dictionaries/kobo/dicthtml-es-ku.zip: dictionaries/tei/spa-kur.tei
dictionaries/stardict/wikdict-es-ku: dictionaries/tei/spa-kur.tei
dictionaries/kobo/dicthtml-es-la.zip: dictionaries/tei/spa-lat.tei
dictionaries/stardict/wikdict-es-la: dictionaries/tei/spa-lat.tei
dictionaries/kobo/dicthtml-es-lt.zip: dictionaries/tei/spa-lit.tei
dictionaries/stardict/wikdict-es-lt: dictionaries/tei/spa-lit.tei
dictionaries/kobo/dicthtml-es-mg.zip: dictionaries/tei/spa-mlg.tei
dictionaries/stardict/wikdict-es-mg: dictionaries/tei/spa-mlg.tei
dictionaries/kobo/dicthtml-es-nl.zip: dictionaries/tei/spa-nld.tei
dictionaries/stardict/wikdict-es-nl: dictionaries/tei/spa-nld.tei
dictionaries/kobo/dicthtml-es-no.zip: dictionaries/tei/spa-nor.tei
dictionaries/stardict/wikdict-es-no: dictionaries/tei/spa-nor.tei
dictionaries/kobo/dicthtml-es-pl.zip: dictionaries/tei/spa-pol.tei
dictionaries/stardict/wikdict-es-pl: dictionaries/tei/spa-pol.tei
dictionaries/kobo/dicthtml-es-pt.zip: dictionaries/tei/spa-por.tei
dictionaries/stardict/wikdict-es-pt: dictionaries/tei/spa-por.tei
dictionaries/kobo/dicthtml-es-ru.zip: dictionaries/tei/spa-rus.tei
dictionaries/stardict/wikdict-es-ru: dictionaries/tei/spa-rus.tei
dictionaries/kobo/dicthtml-es-sv.zip: dictionaries/tei/spa-swe.tei
dictionaries/stardict/wikdict-es-sv: dictionaries/tei/spa-swe.tei
dictionaries/kobo/dicthtml-es-tr.zip: dictionaries/tei/spa-tur.tei
dictionaries/stardict/wikdict-es-tr: dictionaries/tei/spa-tur.tei
dictionaries/kobo/dicthtml-es-zh.zip: dictionaries/tei/spa-zho.tei
dictionaries/stardict/wikdict-es-zh: dictionaries/tei/spa-zho.tei
dictionaries/kobo/dicthtml-fi-bg.zip: dictionaries/tei/fin-bul.tei
dictionaries/stardict/wikdict-fi-bg: dictionaries/tei/fin-bul.tei
dictionaries/kobo/dicthtml-fi-ca.zip: dictionaries/tei/fin-cat.tei
dictionaries/stardict/wikdict-fi-ca: dictionaries/tei/fin-cat.tei
dictionaries/kobo/dicthtml-fi-de.zip: dictionaries/tei/fin-deu.tei
dictionaries/stardict/wikdict-fi-de: dictionaries/tei/fin-deu.tei
dictionaries/kobo/dicthtml-fi-el.zip: dictionaries/tei/fin-ell.tei
dictionaries/stardict/wikdict-fi-el: dictionaries/tei/fin-ell.tei
dictionaries/kobo/dicthtml-fi-en.zip: dictionaries/tei/fin-eng.tei
dictionaries/stardict/wikdict-fi-en: dictionaries/tei/fin-eng.tei
dictionaries/kobo/dicthtml-fi-es.zip: dictionaries/tei/fin-spa.tei
dictionaries/stardict/wikdict-fi-es: dictionaries/tei/fin-spa.tei
dictionaries/kobo/dicthtml-fi-fr.zip: dictionaries/tei/fin-fra.tei
dictionaries/stardict/wikdict-fi-fr: dictionaries/tei/fin-fra.tei
dictionaries/kobo/dicthtml-fi-ga.zip: dictionaries/tei/fin-gle.tei
dictionaries/stardict/wikdict-fi-ga: dictionaries/tei/fin-gle.tei
dictionaries/kobo/dicthtml-fi-id.zip: dictionaries/tei/fin-ind.tei
dictionaries/stardict/wikdict-fi-id: dictionaries/tei/fin-ind.tei
dictionaries/kobo/dicthtml-fi-it.zip: dictionaries/tei/fin-ita.tei
dictionaries/stardict/wikdict-fi-it: dictionaries/tei/fin-ita.tei
dictionaries/kobo/dicthtml-fi-ja.zip: dictionaries/tei/fin-jpn.tei
dictionaries/stardict/wikdict-fi-ja: dictionaries/tei/fin-jpn.tei
dictionaries/kobo/dicthtml-fi-ku.zip: dictionaries/tei/fin-kur.tei
dictionaries/stardict/wikdict-fi-ku: dictionaries/tei/fin-kur.tei
dictionaries/kobo/dicthtml-fi-la.zip: dictionaries/tei/fin-lat.tei
dictionaries/stardict/wikdict-fi-la: dictionaries/tei/fin-lat.tei
dictionaries/kobo/dicthtml-fi-lt.zip: dictionaries/tei/fin-lit.tei
dictionaries/stardict/wikdict-fi-lt: dictionaries/tei/fin-lit.tei
dictionaries/kobo/dicthtml-fi-mg.zip: dictionaries/tei/fin-mlg.tei
dictionaries/stardict/wikdict-fi-mg: dictionaries/tei/fin-mlg.tei
dictionaries/kobo/dicthtml-fi-nl.zip: dictionaries/tei/fin-nld.tei
dictionaries/stardict/wikdict-fi-nl: dictionaries/tei/fin-nld.tei
dictionaries/kobo/dicthtml-fi-no.zip: dictionaries/tei/fin-nor.tei
dictionaries/stardict/wikdict-fi-no: dictionaries/tei/fin-nor.tei
dictionaries/kobo/dicthtml-fi-pl.zip: dictionaries/tei/fin-pol.tei
dictionaries/stardict/wikdict-fi-pl: dictionaries/tei/fin-pol.tei
dictionaries/kobo/dicthtml-fi-pt.zip: dictionaries/tei/fin-por.tei
dictionaries/stardict/wikdict-fi-pt: dictionaries/tei/fin-por.tei
dictionaries/kobo/dicthtml-fi-ru.zip: dictionaries/tei/fin-rus.tei
dictionaries/stardict/wikdict-fi-ru: dictionaries/tei/fin-rus.tei
dictionaries/kobo/dicthtml-fi-sv.zip: dictionaries/tei/fin-swe.tei
dictionaries/stardict/wikdict-fi-sv: dictionaries/tei/fin-swe.tei
dictionaries/kobo/dicthtml-fi-tr.zip: dictionaries/tei/fin-tur.tei
dictionaries/stardict/wikdict-fi-tr: dictionaries/tei/fin-tur.tei
dictionaries/kobo/dicthtml-fi-zh.zip: dictionaries/tei/fin-zho.tei
dictionaries/stardict/wikdict-fi-zh: dictionaries/tei/fin-zho.tei
dictionaries/kobo/dicthtml-fr-bg.zip: dictionaries/tei/fra-bul.tei
dictionaries/stardict/wikdict-fr-bg: dictionaries/tei/fra-bul.tei
dictionaries/kobo/dicthtml-fr-ca.zip: dictionaries/tei/fra-cat.tei
dictionaries/stardict/wikdict-fr-ca: dictionaries/tei/fra-cat.tei
dictionaries/kobo/dicthtml-fr-de.zip: dictionaries/tei/fra-deu.tei
dictionaries/stardict/wikdict-fr-de: dictionaries/tei/fra-deu.tei
dictionaries/kobo/dicthtml-fr-el.zip: dictionaries/tei/fra-ell.tei
dictionaries/stardict/wikdict-fr-el: dictionaries/tei/fra-ell.tei
dictionaries/kobo/dicthtml-fr-en.zip: dictionaries/tei/fra-eng.tei
dictionaries/stardict/wikdict-fr-en: dictionaries/tei/fra-eng.tei
dictionaries/kobo/dicthtml-fr-es.zip: dictionaries/tei/fra-spa.tei
dictionaries/stardict/wikdict-fr-es: dictionaries/tei/fra-spa.tei
dictionaries/kobo/dicthtml-fr-fi.zip: dictionaries/tei/fra-fin.tei
dictionaries/stardict/wikdict-fr-fi: dictionaries/tei/fra-fin.tei
dictionaries/kobo/dicthtml-fr-ga.zip: dictionaries/tei/fra-gle.tei
dictionaries/stardict/wikdict-fr-ga: dictionaries/tei/fra-gle.tei
dictionaries/kobo/dicthtml-fr-id.zip: dictionaries/tei/fra-ind.tei
dictionaries/stardict/wikdict-fr-id: dictionaries/tei/fra-ind.tei
dictionaries/kobo/dicthtml-fr-it.zip: dictionaries/tei/fra-ita.tei
dictionaries/stardict/wikdict-fr-it: dictionaries/tei/fra-ita.tei
dictionaries/kobo/dicthtml-fr-ja.zip: dictionaries/tei/fra-jpn.tei
dictionaries/stardict/wikdict-fr-ja: dictionaries/tei/fra-jpn.tei
dictionaries/kobo/dicthtml-fr-ku.zip: dictionaries/tei/fra-kur.tei
dictionaries/stardict/wikdict-fr-ku: dictionaries/tei/fra-kur.tei
dictionaries/kobo/dicthtml-fr-la.zip: dictionaries/tei/fra-lat.tei
dictionaries/stardict/wikdict-fr-la: dictionaries/tei/fra-lat.tei
dictionaries/kobo/dicthtml-fr-lt.zip: dictionaries/tei/fra-lit.tei
dictionaries/stardict/wikdict-fr-lt: dictionaries/tei/fra-lit.tei
dictionaries/kobo/dicthtml-fr-mg.zip: dictionaries/tei/fra-mlg.tei
dictionaries/stardict/wikdict-fr-mg: dictionaries/tei/fra-mlg.tei
dictionaries/kobo/dicthtml-fr-nl.zip: dictionaries/tei/fra-nld.tei
dictionaries/stardict/wikdict-fr-nl: dictionaries/tei/fra-nld.tei
dictionaries/kobo/dicthtml-fr-no.zip: dictionaries/tei/fra-nor.tei
dictionaries/stardict/wikdict-fr-no: dictionaries/tei/fra-nor.tei
dictionaries/kobo/dicthtml-fr-pl.zip: dictionaries/tei/fra-pol.tei
dictionaries/stardict/wikdict-fr-pl: dictionaries/tei/fra-pol.tei
dictionaries/kobo/dicthtml-fr-pt.zip: dictionaries/tei/fra-por.tei
dictionaries/stardict/wikdict-fr-pt: dictionaries/tei/fra-por.tei
dictionaries/kobo/dicthtml-fr-ru.zip: dictionaries/tei/fra-rus.tei
dictionaries/stardict/wikdict-fr-ru: dictionaries/tei/fra-rus.tei
dictionaries/kobo/dicthtml-fr-sv.zip: dictionaries/tei/fra-swe.tei
dictionaries/stardict/wikdict-fr-sv: dictionaries/tei/fra-swe.tei
dictionaries/kobo/dicthtml-fr-tr.zip: dictionaries/tei/fra-tur.tei
dictionaries/stardict/wikdict-fr-tr: dictionaries/tei/fra-tur.tei
dictionaries/kobo/dicthtml-fr-zh.zip: dictionaries/tei/fra-zho.tei
dictionaries/stardict/wikdict-fr-zh: dictionaries/tei/fra-zho.tei
dictionaries/kobo/dicthtml-ga-bg.zip: dictionaries/tei/gle-bul.tei
dictionaries/stardict/wikdict-ga-bg: dictionaries/tei/gle-bul.tei
dictionaries/kobo/dicthtml-ga-ca.zip: dictionaries/tei/gle-cat.tei
dictionaries/stardict/wikdict-ga-ca: dictionaries/tei/gle-cat.tei
dictionaries/kobo/dicthtml-ga-de.zip: dictionaries/tei/gle-deu.tei
dictionaries/stardict/wikdict-ga-de: dictionaries/tei/gle-deu.tei
dictionaries/kobo/dicthtml-ga-el.zip: dictionaries/tei/gle-ell.tei
dictionaries/stardict/wikdict-ga-el: dictionaries/tei/gle-ell.tei
dictionaries/kobo/dicthtml-ga-en.zip: dictionaries/tei/gle-eng.tei
dictionaries/stardict/wikdict-ga-en: dictionaries/tei/gle-eng.tei
dictionaries/kobo/dicthtml-ga-es.zip: dictionaries/tei/gle-spa.tei
dictionaries/stardict/wikdict-ga-es: dictionaries/tei/gle-spa.tei
dictionaries/kobo/dicthtml-ga-fi.zip: dictionaries/tei/gle-fin.tei
dictionaries/stardict/wikdict-ga-fi: dictionaries/tei/gle-fin.tei
dictionaries/kobo/dicthtml-ga-fr.zip: dictionaries/tei/gle-fra.tei
dictionaries/stardict/wikdict-ga-fr: dictionaries/tei/gle-fra.tei
dictionaries/kobo/dicthtml-ga-id.zip: dictionaries/tei/gle-ind.tei
dictionaries/stardict/wikdict-ga-id: dictionaries/tei/gle-ind.tei
dictionaries/kobo/dicthtml-ga-it.zip: dictionaries/tei/gle-ita.tei
dictionaries/stardict/wikdict-ga-it: dictionaries/tei/gle-ita.tei
dictionaries/kobo/dicthtml-ga-ja.zip: dictionaries/tei/gle-jpn.tei
dictionaries/stardict/wikdict-ga-ja: dictionaries/tei/gle-jpn.tei
dictionaries/kobo/dicthtml-ga-ku.zip: dictionaries/tei/gle-kur.tei
dictionaries/stardict/wikdict-ga-ku: dictionaries/tei/gle-kur.tei
dictionaries/kobo/dicthtml-ga-la.zip: dictionaries/tei/gle-lat.tei
dictionaries/stardict/wikdict-ga-la: dictionaries/tei/gle-lat.tei
dictionaries/kobo/dicthtml-ga-lt.zip: dictionaries/tei/gle-lit.tei
dictionaries/stardict/wikdict-ga-lt: dictionaries/tei/gle-lit.tei
dictionaries/kobo/dicthtml-ga-mg.zip: dictionaries/tei/gle-mlg.tei
dictionaries/stardict/wikdict-ga-mg: dictionaries/tei/gle-mlg.tei
dictionaries/kobo/dicthtml-ga-nl.zip: dictionaries/tei/gle-nld.tei
dictionaries/stardict/wikdict-ga-nl: dictionaries/tei/gle-nld.tei
dictionaries/kobo/dicthtml-ga-no.zip: dictionaries/tei/gle-nor.tei
dictionaries/stardict/wikdict-ga-no: dictionaries/tei/gle-nor.tei
dictionaries/kobo/dicthtml-ga-pl.zip: dictionaries/tei/gle-pol.tei
dictionaries/stardict/wikdict-ga-pl: dictionaries/tei/gle-pol.tei
dictionaries/kobo/dicthtml-ga-pt.zip: dictionaries/tei/gle-por.tei
dictionaries/stardict/wikdict-ga-pt: dictionaries/tei/gle-por.tei
dictionaries/kobo/dicthtml-ga-ru.zip: dictionaries/tei/gle-rus.tei
dictionaries/stardict/wikdict-ga-ru: dictionaries/tei/gle-rus.tei
dictionaries/kobo/dicthtml-ga-sv.zip: dictionaries/tei/gle-swe.tei
dictionaries/stardict/wikdict-ga-sv: dictionaries/tei/gle-swe.tei
dictionaries/kobo/dicthtml-ga-tr.zip: dictionaries/tei/gle-tur.tei
dictionaries/stardict/wikdict-ga-tr: dictionaries/tei/gle-tur.tei
dictionaries/kobo/dicthtml-ga-zh.zip: dictionaries/tei/gle-zho.tei
dictionaries/stardict/wikdict-ga-zh: dictionaries/tei/gle-zho.tei
dictionaries/kobo/dicthtml-id-bg.zip: dictionaries/tei/ind-bul.tei
dictionaries/stardict/wikdict-id-bg: dictionaries/tei/ind-bul.tei
dictionaries/kobo/dicthtml-id-ca.zip: dictionaries/tei/ind-cat.tei
dictionaries/stardict/wikdict-id-ca: dictionaries/tei/ind-cat.tei
dictionaries/kobo/dicthtml-id-de.zip: dictionaries/tei/ind-deu.tei
dictionaries/stardict/wikdict-id-de: dictionaries/tei/ind-deu.tei
dictionaries/kobo/dicthtml-id-el.zip: dictionaries/tei/ind-ell.tei
dictionaries/stardict/wikdict-id-el: dictionaries/tei/ind-ell.tei
dictionaries/kobo/dicthtml-id-en.zip: dictionaries/tei/ind-eng.tei
dictionaries/stardict/wikdict-id-en: dictionaries/tei/ind-eng.tei
dictionaries/kobo/dicthtml-id-es.zip: dictionaries/tei/ind-spa.tei
dictionaries/stardict/wikdict-id-es: dictionaries/tei/ind-spa.tei
dictionaries/kobo/dicthtml-id-fi.zip: dictionaries/tei/ind-fin.tei
dictionaries/stardict/wikdict-id-fi: dictionaries/tei/ind-fin.tei
dictionaries/kobo/dicthtml-id-fr.zip: dictionaries/tei/ind-fra.tei
dictionaries/stardict/wikdict-id-fr: dictionaries/tei/ind-fra.tei
dictionaries/kobo/dicthtml-id-ga.zip: dictionaries/tei/ind-gle.tei
dictionaries/stardict/wikdict-id-ga: dictionaries/tei/ind-gle.tei
dictionaries/kobo/dicthtml-id-it.zip: dictionaries/tei/ind-ita.tei
dictionaries/stardict/wikdict-id-it: dictionaries/tei/ind-ita.tei
dictionaries/kobo/dicthtml-id-ja.zip: dictionaries/tei/ind-jpn.tei
dictionaries/stardict/wikdict-id-ja: dictionaries/tei/ind-jpn.tei
dictionaries/kobo/dicthtml-id-ku.zip: dictionaries/tei/ind-kur.tei
dictionaries/stardict/wikdict-id-ku: dictionaries/tei/ind-kur.tei
dictionaries/kobo/dicthtml-id-la.zip: dictionaries/tei/ind-lat.tei
dictionaries/stardict/wikdict-id-la: dictionaries/tei/ind-lat.tei
dictionaries/kobo/dicthtml-id-lt.zip: dictionaries/tei/ind-lit.tei
dictionaries/stardict/wikdict-id-lt: dictionaries/tei/ind-lit.tei
dictionaries/kobo/dicthtml-id-mg.zip: dictionaries/tei/ind-mlg.tei
dictionaries/stardict/wikdict-id-mg: dictionaries/tei/ind-mlg.tei
dictionaries/kobo/dicthtml-id-nl.zip: dictionaries/tei/ind-nld.tei
dictionaries/stardict/wikdict-id-nl: dictionaries/tei/ind-nld.tei
dictionaries/kobo/dicthtml-id-no.zip: dictionaries/tei/ind-nor.tei
dictionaries/stardict/wikdict-id-no: dictionaries/tei/ind-nor.tei
dictionaries/kobo/dicthtml-id-pl.zip: dictionaries/tei/ind-pol.tei
dictionaries/stardict/wikdict-id-pl: dictionaries/tei/ind-pol.tei
dictionaries/kobo/dicthtml-id-pt.zip: dictionaries/tei/ind-por.tei
dictionaries/stardict/wikdict-id-pt: dictionaries/tei/ind-por.tei
dictionaries/kobo/dicthtml-id-ru.zip: dictionaries/tei/ind-rus.tei
dictionaries/stardict/wikdict-id-ru: dictionaries/tei/ind-rus.tei
dictionaries/kobo/dicthtml-id-sv.zip: dictionaries/tei/ind-swe.tei
dictionaries/stardict/wikdict-id-sv: dictionaries/tei/ind-swe.tei
dictionaries/kobo/dicthtml-id-tr.zip: dictionaries/tei/ind-tur.tei
dictionaries/stardict/wikdict-id-tr: dictionaries/tei/ind-tur.tei
dictionaries/kobo/dicthtml-id-zh.zip: dictionaries/tei/ind-zho.tei
dictionaries/stardict/wikdict-id-zh: dictionaries/tei/ind-zho.tei
dictionaries/kobo/dicthtml-it-bg.zip: dictionaries/tei/ita-bul.tei
dictionaries/stardict/wikdict-it-bg: dictionaries/tei/ita-bul.tei
dictionaries/kobo/dicthtml-it-ca.zip: dictionaries/tei/ita-cat.tei
dictionaries/stardict/wikdict-it-ca: dictionaries/tei/ita-cat.tei
dictionaries/kobo/dicthtml-it-de.zip: dictionaries/tei/ita-deu.tei
dictionaries/stardict/wikdict-it-de: dictionaries/tei/ita-deu.tei
dictionaries/kobo/dicthtml-it-el.zip: dictionaries/tei/ita-ell.tei
dictionaries/stardict/wikdict-it-el: dictionaries/tei/ita-ell.tei
dictionaries/kobo/dicthtml-it-en.zip: dictionaries/tei/ita-eng.tei
dictionaries/stardict/wikdict-it-en: dictionaries/tei/ita-eng.tei
dictionaries/kobo/dicthtml-it-es.zip: dictionaries/tei/ita-spa.tei
dictionaries/stardict/wikdict-it-es: dictionaries/tei/ita-spa.tei
dictionaries/kobo/dicthtml-it-fi.zip: dictionaries/tei/ita-fin.tei
dictionaries/stardict/wikdict-it-fi: dictionaries/tei/ita-fin.tei
dictionaries/kobo/dicthtml-it-fr.zip: dictionaries/tei/ita-fra.tei
dictionaries/stardict/wikdict-it-fr: dictionaries/tei/ita-fra.tei
dictionaries/kobo/dicthtml-it-ga.zip: dictionaries/tei/ita-gle.tei
dictionaries/stardict/wikdict-it-ga: dictionaries/tei/ita-gle.tei
dictionaries/kobo/dicthtml-it-id.zip: dictionaries/tei/ita-ind.tei
dictionaries/stardict/wikdict-it-id: dictionaries/tei/ita-ind.tei
dictionaries/kobo/dicthtml-it-ja.zip: dictionaries/tei/ita-jpn.tei
dictionaries/stardict/wikdict-it-ja: dictionaries/tei/ita-jpn.tei
dictionaries/kobo/dicthtml-it-ku.zip: dictionaries/tei/ita-kur.tei
dictionaries/stardict/wikdict-it-ku: dictionaries/tei/ita-kur.tei
dictionaries/kobo/dicthtml-it-la.zip: dictionaries/tei/ita-lat.tei
dictionaries/stardict/wikdict-it-la: dictionaries/tei/ita-lat.tei
dictionaries/kobo/dicthtml-it-lt.zip: dictionaries/tei/ita-lit.tei
dictionaries/stardict/wikdict-it-lt: dictionaries/tei/ita-lit.tei
dictionaries/kobo/dicthtml-it-mg.zip: dictionaries/tei/ita-mlg.tei
dictionaries/stardict/wikdict-it-mg: dictionaries/tei/ita-mlg.tei
dictionaries/kobo/dicthtml-it-nl.zip: dictionaries/tei/ita-nld.tei
dictionaries/stardict/wikdict-it-nl: dictionaries/tei/ita-nld.tei
dictionaries/kobo/dicthtml-it-no.zip: dictionaries/tei/ita-nor.tei
dictionaries/stardict/wikdict-it-no: dictionaries/tei/ita-nor.tei
dictionaries/kobo/dicthtml-it-pl.zip: dictionaries/tei/ita-pol.tei
dictionaries/stardict/wikdict-it-pl: dictionaries/tei/ita-pol.tei
dictionaries/kobo/dicthtml-it-pt.zip: dictionaries/tei/ita-por.tei
dictionaries/stardict/wikdict-it-pt: dictionaries/tei/ita-por.tei
dictionaries/kobo/dicthtml-it-ru.zip: dictionaries/tei/ita-rus.tei
dictionaries/stardict/wikdict-it-ru: dictionaries/tei/ita-rus.tei
dictionaries/kobo/dicthtml-it-sv.zip: dictionaries/tei/ita-swe.tei
dictionaries/stardict/wikdict-it-sv: dictionaries/tei/ita-swe.tei
dictionaries/kobo/dicthtml-it-tr.zip: dictionaries/tei/ita-tur.tei
dictionaries/stardict/wikdict-it-tr: dictionaries/tei/ita-tur.tei
dictionaries/kobo/dicthtml-it-zh.zip: dictionaries/tei/ita-zho.tei
dictionaries/stardict/wikdict-it-zh: dictionaries/tei/ita-zho.tei
dictionaries/kobo/dicthtml-ja-bg.zip: dictionaries/tei/jpn-bul.tei
dictionaries/stardict/wikdict-ja-bg: dictionaries/tei/jpn-bul.tei
dictionaries/kobo/dicthtml-ja-ca.zip: dictionaries/tei/jpn-cat.tei
dictionaries/stardict/wikdict-ja-ca: dictionaries/tei/jpn-cat.tei
dictionaries/kobo/dicthtml-ja-de.zip: dictionaries/tei/jpn-deu.tei
dictionaries/stardict/wikdict-ja-de: dictionaries/tei/jpn-deu.tei
dictionaries/kobo/dicthtml-ja-el.zip: dictionaries/tei/jpn-ell.tei
dictionaries/stardict/wikdict-ja-el: dictionaries/tei/jpn-ell.tei
dictionaries/kobo/dicthtml-ja-en.zip: dictionaries/tei/jpn-eng.tei
dictionaries/stardict/wikdict-ja-en: dictionaries/tei/jpn-eng.tei
dictionaries/kobo/dicthtml-ja-es.zip: dictionaries/tei/jpn-spa.tei
dictionaries/stardict/wikdict-ja-es: dictionaries/tei/jpn-spa.tei
dictionaries/kobo/dicthtml-ja-fi.zip: dictionaries/tei/jpn-fin.tei
dictionaries/stardict/wikdict-ja-fi: dictionaries/tei/jpn-fin.tei
dictionaries/kobo/dicthtml-ja-fr.zip: dictionaries/tei/jpn-fra.tei
dictionaries/stardict/wikdict-ja-fr: dictionaries/tei/jpn-fra.tei
dictionaries/kobo/dicthtml-ja-ga.zip: dictionaries/tei/jpn-gle.tei
dictionaries/stardict/wikdict-ja-ga: dictionaries/tei/jpn-gle.tei
dictionaries/kobo/dicthtml-ja-id.zip: dictionaries/tei/jpn-ind.tei
dictionaries/stardict/wikdict-ja-id: dictionaries/tei/jpn-ind.tei
dictionaries/kobo/dicthtml-ja-it.zip: dictionaries/tei/jpn-ita.tei
dictionaries/stardict/wikdict-ja-it: dictionaries/tei/jpn-ita.tei
dictionaries/kobo/dicthtml-ja-ku.zip: dictionaries/tei/jpn-kur.tei
dictionaries/stardict/wikdict-ja-ku: dictionaries/tei/jpn-kur.tei
dictionaries/kobo/dicthtml-ja-la.zip: dictionaries/tei/jpn-lat.tei
dictionaries/stardict/wikdict-ja-la: dictionaries/tei/jpn-lat.tei
dictionaries/kobo/dicthtml-ja-lt.zip: dictionaries/tei/jpn-lit.tei
dictionaries/stardict/wikdict-ja-lt: dictionaries/tei/jpn-lit.tei
dictionaries/kobo/dicthtml-ja-mg.zip: dictionaries/tei/jpn-mlg.tei
dictionaries/stardict/wikdict-ja-mg: dictionaries/tei/jpn-mlg.tei
dictionaries/kobo/dicthtml-ja-nl.zip: dictionaries/tei/jpn-nld.tei
dictionaries/stardict/wikdict-ja-nl: dictionaries/tei/jpn-nld.tei
dictionaries/kobo/dicthtml-ja-no.zip: dictionaries/tei/jpn-nor.tei
dictionaries/stardict/wikdict-ja-no: dictionaries/tei/jpn-nor.tei
dictionaries/kobo/dicthtml-ja-pl.zip: dictionaries/tei/jpn-pol.tei
dictionaries/stardict/wikdict-ja-pl: dictionaries/tei/jpn-pol.tei
dictionaries/kobo/dicthtml-ja-pt.zip: dictionaries/tei/jpn-por.tei
dictionaries/stardict/wikdict-ja-pt: dictionaries/tei/jpn-por.tei
dictionaries/kobo/dicthtml-ja-ru.zip: dictionaries/tei/jpn-rus.tei
dictionaries/stardict/wikdict-ja-ru: dictionaries/tei/jpn-rus.tei
dictionaries/kobo/dicthtml-ja-sv.zip: dictionaries/tei/jpn-swe.tei
dictionaries/stardict/wikdict-ja-sv: dictionaries/tei/jpn-swe.tei
dictionaries/kobo/dicthtml-ja-tr.zip: dictionaries/tei/jpn-tur.tei
dictionaries/stardict/wikdict-ja-tr: dictionaries/tei/jpn-tur.tei
dictionaries/kobo/dicthtml-ja-zh.zip: dictionaries/tei/jpn-zho.tei
dictionaries/stardict/wikdict-ja-zh: dictionaries/tei/jpn-zho.tei
dictionaries/kobo/dicthtml-ku-bg.zip: dictionaries/tei/kur-bul.tei
dictionaries/stardict/wikdict-ku-bg: dictionaries/tei/kur-bul.tei
dictionaries/kobo/dicthtml-ku-ca.zip: dictionaries/tei/kur-cat.tei
dictionaries/stardict/wikdict-ku-ca: dictionaries/tei/kur-cat.tei
dictionaries/kobo/dicthtml-ku-de.zip: dictionaries/tei/kur-deu.tei
dictionaries/stardict/wikdict-ku-de: dictionaries/tei/kur-deu.tei
dictionaries/kobo/dicthtml-ku-el.zip: dictionaries/tei/kur-ell.tei
dictionaries/stardict/wikdict-ku-el: dictionaries/tei/kur-ell.tei
dictionaries/kobo/dicthtml-ku-en.zip: dictionaries/tei/kur-eng.tei
dictionaries/stardict/wikdict-ku-en: dictionaries/tei/kur-eng.tei
dictionaries/kobo/dicthtml-ku-es.zip: dictionaries/tei/kur-spa.tei
dictionaries/stardict/wikdict-ku-es: dictionaries/tei/kur-spa.tei
dictionaries/kobo/dicthtml-ku-fi.zip: dictionaries/tei/kur-fin.tei
dictionaries/stardict/wikdict-ku-fi: dictionaries/tei/kur-fin.tei
dictionaries/kobo/dicthtml-ku-fr.zip: dictionaries/tei/kur-fra.tei
dictionaries/stardict/wikdict-ku-fr: dictionaries/tei/kur-fra.tei
dictionaries/kobo/dicthtml-ku-ga.zip: dictionaries/tei/kur-gle.tei
dictionaries/stardict/wikdict-ku-ga: dictionaries/tei/kur-gle.tei
dictionaries/kobo/dicthtml-ku-id.zip: dictionaries/tei/kur-ind.tei
dictionaries/stardict/wikdict-ku-id: dictionaries/tei/kur-ind.tei
dictionaries/kobo/dicthtml-ku-it.zip: dictionaries/tei/kur-ita.tei
dictionaries/stardict/wikdict-ku-it: dictionaries/tei/kur-ita.tei
dictionaries/kobo/dicthtml-ku-ja.zip: dictionaries/tei/kur-jpn.tei
dictionaries/stardict/wikdict-ku-ja: dictionaries/tei/kur-jpn.tei
dictionaries/kobo/dicthtml-ku-la.zip: dictionaries/tei/kur-lat.tei
dictionaries/stardict/wikdict-ku-la: dictionaries/tei/kur-lat.tei
dictionaries/kobo/dicthtml-ku-lt.zip: dictionaries/tei/kur-lit.tei
dictionaries/stardict/wikdict-ku-lt: dictionaries/tei/kur-lit.tei
dictionaries/kobo/dicthtml-ku-mg.zip: dictionaries/tei/kur-mlg.tei
dictionaries/stardict/wikdict-ku-mg: dictionaries/tei/kur-mlg.tei
dictionaries/kobo/dicthtml-ku-nl.zip: dictionaries/tei/kur-nld.tei
dictionaries/stardict/wikdict-ku-nl: dictionaries/tei/kur-nld.tei
dictionaries/kobo/dicthtml-ku-no.zip: dictionaries/tei/kur-nor.tei
dictionaries/stardict/wikdict-ku-no: dictionaries/tei/kur-nor.tei
dictionaries/kobo/dicthtml-ku-pl.zip: dictionaries/tei/kur-pol.tei
dictionaries/stardict/wikdict-ku-pl: dictionaries/tei/kur-pol.tei
dictionaries/kobo/dicthtml-ku-pt.zip: dictionaries/tei/kur-por.tei
dictionaries/stardict/wikdict-ku-pt: dictionaries/tei/kur-por.tei
dictionaries/kobo/dicthtml-ku-ru.zip: dictionaries/tei/kur-rus.tei
dictionaries/stardict/wikdict-ku-ru: dictionaries/tei/kur-rus.tei
dictionaries/kobo/dicthtml-ku-sv.zip: dictionaries/tei/kur-swe.tei
dictionaries/stardict/wikdict-ku-sv: dictionaries/tei/kur-swe.tei
dictionaries/kobo/dicthtml-ku-tr.zip: dictionaries/tei/kur-tur.tei
dictionaries/stardict/wikdict-ku-tr: dictionaries/tei/kur-tur.tei
dictionaries/kobo/dicthtml-ku-zh.zip: dictionaries/tei/kur-zho.tei
dictionaries/stardict/wikdict-ku-zh: dictionaries/tei/kur-zho.tei
dictionaries/kobo/dicthtml-la-bg.zip: dictionaries/tei/lat-bul.tei
dictionaries/stardict/wikdict-la-bg: dictionaries/tei/lat-bul.tei
dictionaries/kobo/dicthtml-la-ca.zip: dictionaries/tei/lat-cat.tei
dictionaries/stardict/wikdict-la-ca: dictionaries/tei/lat-cat.tei
dictionaries/kobo/dicthtml-la-de.zip: dictionaries/tei/lat-deu.tei
dictionaries/stardict/wikdict-la-de: dictionaries/tei/lat-deu.tei
dictionaries/kobo/dicthtml-la-el.zip: dictionaries/tei/lat-ell.tei
dictionaries/stardict/wikdict-la-el: dictionaries/tei/lat-ell.tei
dictionaries/kobo/dicthtml-la-en.zip: dictionaries/tei/lat-eng.tei
dictionaries/stardict/wikdict-la-en: dictionaries/tei/lat-eng.tei
dictionaries/kobo/dicthtml-la-es.zip: dictionaries/tei/lat-spa.tei
dictionaries/stardict/wikdict-la-es: dictionaries/tei/lat-spa.tei
dictionaries/kobo/dicthtml-la-fi.zip: dictionaries/tei/lat-fin.tei
dictionaries/stardict/wikdict-la-fi: dictionaries/tei/lat-fin.tei
dictionaries/kobo/dicthtml-la-fr.zip: dictionaries/tei/lat-fra.tei
dictionaries/stardict/wikdict-la-fr: dictionaries/tei/lat-fra.tei
dictionaries/kobo/dicthtml-la-ga.zip: dictionaries/tei/lat-gle.tei
dictionaries/stardict/wikdict-la-ga: dictionaries/tei/lat-gle.tei
dictionaries/kobo/dicthtml-la-id.zip: dictionaries/tei/lat-ind.tei
dictionaries/stardict/wikdict-la-id: dictionaries/tei/lat-ind.tei
dictionaries/kobo/dicthtml-la-it.zip: dictionaries/tei/lat-ita.tei
dictionaries/stardict/wikdict-la-it: dictionaries/tei/lat-ita.tei
dictionaries/kobo/dicthtml-la-ja.zip: dictionaries/tei/lat-jpn.tei
dictionaries/stardict/wikdict-la-ja: dictionaries/tei/lat-jpn.tei
dictionaries/kobo/dicthtml-la-ku.zip: dictionaries/tei/lat-kur.tei
dictionaries/stardict/wikdict-la-ku: dictionaries/tei/lat-kur.tei
dictionaries/kobo/dicthtml-la-lt.zip: dictionaries/tei/lat-lit.tei
dictionaries/stardict/wikdict-la-lt: dictionaries/tei/lat-lit.tei
dictionaries/kobo/dicthtml-la-mg.zip: dictionaries/tei/lat-mlg.tei
dictionaries/stardict/wikdict-la-mg: dictionaries/tei/lat-mlg.tei
dictionaries/kobo/dicthtml-la-nl.zip: dictionaries/tei/lat-nld.tei
dictionaries/stardict/wikdict-la-nl: dictionaries/tei/lat-nld.tei
dictionaries/kobo/dicthtml-la-no.zip: dictionaries/tei/lat-nor.tei
dictionaries/stardict/wikdict-la-no: dictionaries/tei/lat-nor.tei
dictionaries/kobo/dicthtml-la-pl.zip: dictionaries/tei/lat-pol.tei
dictionaries/stardict/wikdict-la-pl: dictionaries/tei/lat-pol.tei
dictionaries/kobo/dicthtml-la-pt.zip: dictionaries/tei/lat-por.tei
dictionaries/stardict/wikdict-la-pt: dictionaries/tei/lat-por.tei
dictionaries/kobo/dicthtml-la-ru.zip: dictionaries/tei/lat-rus.tei
dictionaries/stardict/wikdict-la-ru: dictionaries/tei/lat-rus.tei
dictionaries/kobo/dicthtml-la-sv.zip: dictionaries/tei/lat-swe.tei
dictionaries/stardict/wikdict-la-sv: dictionaries/tei/lat-swe.tei
dictionaries/kobo/dicthtml-la-tr.zip: dictionaries/tei/lat-tur.tei
dictionaries/stardict/wikdict-la-tr: dictionaries/tei/lat-tur.tei
dictionaries/kobo/dicthtml-la-zh.zip: dictionaries/tei/lat-zho.tei
dictionaries/stardict/wikdict-la-zh: dictionaries/tei/lat-zho.tei
dictionaries/kobo/dicthtml-lt-bg.zip: dictionaries/tei/lit-bul.tei
dictionaries/stardict/wikdict-lt-bg: dictionaries/tei/lit-bul.tei
dictionaries/kobo/dicthtml-lt-ca.zip: dictionaries/tei/lit-cat.tei
dictionaries/stardict/wikdict-lt-ca: dictionaries/tei/lit-cat.tei
dictionaries/kobo/dicthtml-lt-de.zip: dictionaries/tei/lit-deu.tei
dictionaries/stardict/wikdict-lt-de: dictionaries/tei/lit-deu.tei
dictionaries/kobo/dicthtml-lt-el.zip: dictionaries/tei/lit-ell.tei
dictionaries/stardict/wikdict-lt-el: dictionaries/tei/lit-ell.tei
dictionaries/kobo/dicthtml-lt-en.zip: dictionaries/tei/lit-eng.tei
dictionaries/stardict/wikdict-lt-en: dictionaries/tei/lit-eng.tei
dictionaries/kobo/dicthtml-lt-es.zip: dictionaries/tei/lit-spa.tei
dictionaries/stardict/wikdict-lt-es: dictionaries/tei/lit-spa.tei
dictionaries/kobo/dicthtml-lt-fi.zip: dictionaries/tei/lit-fin.tei
dictionaries/stardict/wikdict-lt-fi: dictionaries/tei/lit-fin.tei
dictionaries/kobo/dicthtml-lt-fr.zip: dictionaries/tei/lit-fra.tei
dictionaries/stardict/wikdict-lt-fr: dictionaries/tei/lit-fra.tei
dictionaries/kobo/dicthtml-lt-ga.zip: dictionaries/tei/lit-gle.tei
dictionaries/stardict/wikdict-lt-ga: dictionaries/tei/lit-gle.tei
dictionaries/kobo/dicthtml-lt-id.zip: dictionaries/tei/lit-ind.tei
dictionaries/stardict/wikdict-lt-id: dictionaries/tei/lit-ind.tei
dictionaries/kobo/dicthtml-lt-it.zip: dictionaries/tei/lit-ita.tei
dictionaries/stardict/wikdict-lt-it: dictionaries/tei/lit-ita.tei
dictionaries/kobo/dicthtml-lt-ja.zip: dictionaries/tei/lit-jpn.tei
dictionaries/stardict/wikdict-lt-ja: dictionaries/tei/lit-jpn.tei
dictionaries/kobo/dicthtml-lt-ku.zip: dictionaries/tei/lit-kur.tei
dictionaries/stardict/wikdict-lt-ku: dictionaries/tei/lit-kur.tei
dictionaries/kobo/dicthtml-lt-la.zip: dictionaries/tei/lit-lat.tei
dictionaries/stardict/wikdict-lt-la: dictionaries/tei/lit-lat.tei
dictionaries/kobo/dicthtml-lt-mg.zip: dictionaries/tei/lit-mlg.tei
dictionaries/stardict/wikdict-lt-mg: dictionaries/tei/lit-mlg.tei
dictionaries/kobo/dicthtml-lt-nl.zip: dictionaries/tei/lit-nld.tei
dictionaries/stardict/wikdict-lt-nl: dictionaries/tei/lit-nld.tei
dictionaries/kobo/dicthtml-lt-no.zip: dictionaries/tei/lit-nor.tei
dictionaries/stardict/wikdict-lt-no: dictionaries/tei/lit-nor.tei
dictionaries/kobo/dicthtml-lt-pl.zip: dictionaries/tei/lit-pol.tei
dictionaries/stardict/wikdict-lt-pl: dictionaries/tei/lit-pol.tei
dictionaries/kobo/dicthtml-lt-pt.zip: dictionaries/tei/lit-por.tei
dictionaries/stardict/wikdict-lt-pt: dictionaries/tei/lit-por.tei
dictionaries/kobo/dicthtml-lt-ru.zip: dictionaries/tei/lit-rus.tei
dictionaries/stardict/wikdict-lt-ru: dictionaries/tei/lit-rus.tei
dictionaries/kobo/dicthtml-lt-sv.zip: dictionaries/tei/lit-swe.tei
dictionaries/stardict/wikdict-lt-sv: dictionaries/tei/lit-swe.tei
dictionaries/kobo/dicthtml-lt-tr.zip: dictionaries/tei/lit-tur.tei
dictionaries/stardict/wikdict-lt-tr: dictionaries/tei/lit-tur.tei
dictionaries/kobo/dicthtml-lt-zh.zip: dictionaries/tei/lit-zho.tei
dictionaries/stardict/wikdict-lt-zh: dictionaries/tei/lit-zho.tei
dictionaries/kobo/dicthtml-mg-bg.zip: dictionaries/tei/mlg-bul.tei
dictionaries/stardict/wikdict-mg-bg: dictionaries/tei/mlg-bul.tei
dictionaries/kobo/dicthtml-mg-ca.zip: dictionaries/tei/mlg-cat.tei
dictionaries/stardict/wikdict-mg-ca: dictionaries/tei/mlg-cat.tei
dictionaries/kobo/dicthtml-mg-de.zip: dictionaries/tei/mlg-deu.tei
dictionaries/stardict/wikdict-mg-de: dictionaries/tei/mlg-deu.tei
dictionaries/kobo/dicthtml-mg-el.zip: dictionaries/tei/mlg-ell.tei
dictionaries/stardict/wikdict-mg-el: dictionaries/tei/mlg-ell.tei
dictionaries/kobo/dicthtml-mg-en.zip: dictionaries/tei/mlg-eng.tei
dictionaries/stardict/wikdict-mg-en: dictionaries/tei/mlg-eng.tei
dictionaries/kobo/dicthtml-mg-es.zip: dictionaries/tei/mlg-spa.tei
dictionaries/stardict/wikdict-mg-es: dictionaries/tei/mlg-spa.tei
dictionaries/kobo/dicthtml-mg-fi.zip: dictionaries/tei/mlg-fin.tei
dictionaries/stardict/wikdict-mg-fi: dictionaries/tei/mlg-fin.tei
dictionaries/kobo/dicthtml-mg-fr.zip: dictionaries/tei/mlg-fra.tei
dictionaries/stardict/wikdict-mg-fr: dictionaries/tei/mlg-fra.tei
dictionaries/kobo/dicthtml-mg-ga.zip: dictionaries/tei/mlg-gle.tei
dictionaries/stardict/wikdict-mg-ga: dictionaries/tei/mlg-gle.tei
dictionaries/kobo/dicthtml-mg-id.zip: dictionaries/tei/mlg-ind.tei
dictionaries/stardict/wikdict-mg-id: dictionaries/tei/mlg-ind.tei
dictionaries/kobo/dicthtml-mg-it.zip: dictionaries/tei/mlg-ita.tei
dictionaries/stardict/wikdict-mg-it: dictionaries/tei/mlg-ita.tei
dictionaries/kobo/dicthtml-mg-ja.zip: dictionaries/tei/mlg-jpn.tei
dictionaries/stardict/wikdict-mg-ja: dictionaries/tei/mlg-jpn.tei
dictionaries/kobo/dicthtml-mg-ku.zip: dictionaries/tei/mlg-kur.tei
dictionaries/stardict/wikdict-mg-ku: dictionaries/tei/mlg-kur.tei
dictionaries/kobo/dicthtml-mg-la.zip: dictionaries/tei/mlg-lat.tei
dictionaries/stardict/wikdict-mg-la: dictionaries/tei/mlg-lat.tei
dictionaries/kobo/dicthtml-mg-lt.zip: dictionaries/tei/mlg-lit.tei
dictionaries/stardict/wikdict-mg-lt: dictionaries/tei/mlg-lit.tei
dictionaries/kobo/dicthtml-mg-nl.zip: dictionaries/tei/mlg-nld.tei
dictionaries/stardict/wikdict-mg-nl: dictionaries/tei/mlg-nld.tei
dictionaries/kobo/dicthtml-mg-no.zip: dictionaries/tei/mlg-nor.tei
dictionaries/stardict/wikdict-mg-no: dictionaries/tei/mlg-nor.tei
dictionaries/kobo/dicthtml-mg-pl.zip: dictionaries/tei/mlg-pol.tei
dictionaries/stardict/wikdict-mg-pl: dictionaries/tei/mlg-pol.tei
dictionaries/kobo/dicthtml-mg-pt.zip: dictionaries/tei/mlg-por.tei
dictionaries/stardict/wikdict-mg-pt: dictionaries/tei/mlg-por.tei
dictionaries/kobo/dicthtml-mg-ru.zip: dictionaries/tei/mlg-rus.tei
dictionaries/stardict/wikdict-mg-ru: dictionaries/tei/mlg-rus.tei
dictionaries/kobo/dicthtml-mg-sv.zip: dictionaries/tei/mlg-swe.tei
dictionaries/stardict/wikdict-mg-sv: dictionaries/tei/mlg-swe.tei
dictionaries/kobo/dicthtml-mg-tr.zip: dictionaries/tei/mlg-tur.tei
dictionaries/stardict/wikdict-mg-tr: dictionaries/tei/mlg-tur.tei
dictionaries/kobo/dicthtml-mg-zh.zip: dictionaries/tei/mlg-zho.tei
dictionaries/stardict/wikdict-mg-zh: dictionaries/tei/mlg-zho.tei
dictionaries/kobo/dicthtml-nl-bg.zip: dictionaries/tei/nld-bul.tei
dictionaries/stardict/wikdict-nl-bg: dictionaries/tei/nld-bul.tei
dictionaries/kobo/dicthtml-nl-ca.zip: dictionaries/tei/nld-cat.tei
dictionaries/stardict/wikdict-nl-ca: dictionaries/tei/nld-cat.tei
dictionaries/kobo/dicthtml-nl-de.zip: dictionaries/tei/nld-deu.tei
dictionaries/stardict/wikdict-nl-de: dictionaries/tei/nld-deu.tei
dictionaries/kobo/dicthtml-nl-el.zip: dictionaries/tei/nld-ell.tei
dictionaries/stardict/wikdict-nl-el: dictionaries/tei/nld-ell.tei
dictionaries/kobo/dicthtml-nl-en.zip: dictionaries/tei/nld-eng.tei
dictionaries/stardict/wikdict-nl-en: dictionaries/tei/nld-eng.tei
dictionaries/kobo/dicthtml-nl-es.zip: dictionaries/tei/nld-spa.tei
dictionaries/stardict/wikdict-nl-es: dictionaries/tei/nld-spa.tei
dictionaries/kobo/dicthtml-nl-fi.zip: dictionaries/tei/nld-fin.tei
dictionaries/stardict/wikdict-nl-fi: dictionaries/tei/nld-fin.tei
dictionaries/kobo/dicthtml-nl-fr.zip: dictionaries/tei/nld-fra.tei
dictionaries/stardict/wikdict-nl-fr: dictionaries/tei/nld-fra.tei
dictionaries/kobo/dicthtml-nl-ga.zip: dictionaries/tei/nld-gle.tei
dictionaries/stardict/wikdict-nl-ga: dictionaries/tei/nld-gle.tei
dictionaries/kobo/dicthtml-nl-id.zip: dictionaries/tei/nld-ind.tei
dictionaries/stardict/wikdict-nl-id: dictionaries/tei/nld-ind.tei
dictionaries/kobo/dicthtml-nl-it.zip: dictionaries/tei/nld-ita.tei
dictionaries/stardict/wikdict-nl-it: dictionaries/tei/nld-ita.tei
dictionaries/kobo/dicthtml-nl-ja.zip: dictionaries/tei/nld-jpn.tei
dictionaries/stardict/wikdict-nl-ja: dictionaries/tei/nld-jpn.tei
dictionaries/kobo/dicthtml-nl-ku.zip: dictionaries/tei/nld-kur.tei
dictionaries/stardict/wikdict-nl-ku: dictionaries/tei/nld-kur.tei
dictionaries/kobo/dicthtml-nl-la.zip: dictionaries/tei/nld-lat.tei
dictionaries/stardict/wikdict-nl-la: dictionaries/tei/nld-lat.tei
dictionaries/kobo/dicthtml-nl-lt.zip: dictionaries/tei/nld-lit.tei
dictionaries/stardict/wikdict-nl-lt: dictionaries/tei/nld-lit.tei
dictionaries/kobo/dicthtml-nl-mg.zip: dictionaries/tei/nld-mlg.tei
dictionaries/stardict/wikdict-nl-mg: dictionaries/tei/nld-mlg.tei
dictionaries/kobo/dicthtml-nl-no.zip: dictionaries/tei/nld-nor.tei
dictionaries/stardict/wikdict-nl-no: dictionaries/tei/nld-nor.tei
dictionaries/kobo/dicthtml-nl-pl.zip: dictionaries/tei/nld-pol.tei
dictionaries/stardict/wikdict-nl-pl: dictionaries/tei/nld-pol.tei
dictionaries/kobo/dicthtml-nl-pt.zip: dictionaries/tei/nld-por.tei
dictionaries/stardict/wikdict-nl-pt: dictionaries/tei/nld-por.tei
dictionaries/kobo/dicthtml-nl-ru.zip: dictionaries/tei/nld-rus.tei
dictionaries/stardict/wikdict-nl-ru: dictionaries/tei/nld-rus.tei
dictionaries/kobo/dicthtml-nl-sv.zip: dictionaries/tei/nld-swe.tei
dictionaries/stardict/wikdict-nl-sv: dictionaries/tei/nld-swe.tei
dictionaries/kobo/dicthtml-nl-tr.zip: dictionaries/tei/nld-tur.tei
dictionaries/stardict/wikdict-nl-tr: dictionaries/tei/nld-tur.tei
dictionaries/kobo/dicthtml-nl-zh.zip: dictionaries/tei/nld-zho.tei
dictionaries/stardict/wikdict-nl-zh: dictionaries/tei/nld-zho.tei
dictionaries/kobo/dicthtml-no-bg.zip: dictionaries/tei/nor-bul.tei
dictionaries/stardict/wikdict-no-bg: dictionaries/tei/nor-bul.tei
dictionaries/kobo/dicthtml-no-ca.zip: dictionaries/tei/nor-cat.tei
dictionaries/stardict/wikdict-no-ca: dictionaries/tei/nor-cat.tei
dictionaries/kobo/dicthtml-no-de.zip: dictionaries/tei/nor-deu.tei
dictionaries/stardict/wikdict-no-de: dictionaries/tei/nor-deu.tei
dictionaries/kobo/dicthtml-no-el.zip: dictionaries/tei/nor-ell.tei
dictionaries/stardict/wikdict-no-el: dictionaries/tei/nor-ell.tei
dictionaries/kobo/dicthtml-no-en.zip: dictionaries/tei/nor-eng.tei
dictionaries/stardict/wikdict-no-en: dictionaries/tei/nor-eng.tei
dictionaries/kobo/dicthtml-no-es.zip: dictionaries/tei/nor-spa.tei
dictionaries/stardict/wikdict-no-es: dictionaries/tei/nor-spa.tei
dictionaries/kobo/dicthtml-no-fi.zip: dictionaries/tei/nor-fin.tei
dictionaries/stardict/wikdict-no-fi: dictionaries/tei/nor-fin.tei
dictionaries/kobo/dicthtml-no-fr.zip: dictionaries/tei/nor-fra.tei
dictionaries/stardict/wikdict-no-fr: dictionaries/tei/nor-fra.tei
dictionaries/kobo/dicthtml-no-ga.zip: dictionaries/tei/nor-gle.tei
dictionaries/stardict/wikdict-no-ga: dictionaries/tei/nor-gle.tei
dictionaries/kobo/dicthtml-no-id.zip: dictionaries/tei/nor-ind.tei
dictionaries/stardict/wikdict-no-id: dictionaries/tei/nor-ind.tei
dictionaries/kobo/dicthtml-no-it.zip: dictionaries/tei/nor-ita.tei
dictionaries/stardict/wikdict-no-it: dictionaries/tei/nor-ita.tei
dictionaries/kobo/dicthtml-no-ja.zip: dictionaries/tei/nor-jpn.tei
dictionaries/stardict/wikdict-no-ja: dictionaries/tei/nor-jpn.tei
dictionaries/kobo/dicthtml-no-ku.zip: dictionaries/tei/nor-kur.tei
dictionaries/stardict/wikdict-no-ku: dictionaries/tei/nor-kur.tei
dictionaries/kobo/dicthtml-no-la.zip: dictionaries/tei/nor-lat.tei
dictionaries/stardict/wikdict-no-la: dictionaries/tei/nor-lat.tei
dictionaries/kobo/dicthtml-no-lt.zip: dictionaries/tei/nor-lit.tei
dictionaries/stardict/wikdict-no-lt: dictionaries/tei/nor-lit.tei
dictionaries/kobo/dicthtml-no-mg.zip: dictionaries/tei/nor-mlg.tei
dictionaries/stardict/wikdict-no-mg: dictionaries/tei/nor-mlg.tei
dictionaries/kobo/dicthtml-no-nl.zip: dictionaries/tei/nor-nld.tei
dictionaries/stardict/wikdict-no-nl: dictionaries/tei/nor-nld.tei
dictionaries/kobo/dicthtml-no-pl.zip: dictionaries/tei/nor-pol.tei
dictionaries/stardict/wikdict-no-pl: dictionaries/tei/nor-pol.tei
dictionaries/kobo/dicthtml-no-pt.zip: dictionaries/tei/nor-por.tei
dictionaries/stardict/wikdict-no-pt: dictionaries/tei/nor-por.tei
dictionaries/kobo/dicthtml-no-ru.zip: dictionaries/tei/nor-rus.tei
dictionaries/stardict/wikdict-no-ru: dictionaries/tei/nor-rus.tei
dictionaries/kobo/dicthtml-no-sv.zip: dictionaries/tei/nor-swe.tei
dictionaries/stardict/wikdict-no-sv: dictionaries/tei/nor-swe.tei
dictionaries/kobo/dicthtml-no-tr.zip: dictionaries/tei/nor-tur.tei
dictionaries/stardict/wikdict-no-tr: dictionaries/tei/nor-tur.tei
dictionaries/kobo/dicthtml-no-zh.zip: dictionaries/tei/nor-zho.tei
dictionaries/stardict/wikdict-no-zh: dictionaries/tei/nor-zho.tei
dictionaries/kobo/dicthtml-pl-bg.zip: dictionaries/tei/pol-bul.tei
dictionaries/stardict/wikdict-pl-bg: dictionaries/tei/pol-bul.tei
dictionaries/kobo/dicthtml-pl-ca.zip: dictionaries/tei/pol-cat.tei
dictionaries/stardict/wikdict-pl-ca: dictionaries/tei/pol-cat.tei
dictionaries/kobo/dicthtml-pl-de.zip: dictionaries/tei/pol-deu.tei
dictionaries/stardict/wikdict-pl-de: dictionaries/tei/pol-deu.tei
dictionaries/kobo/dicthtml-pl-el.zip: dictionaries/tei/pol-ell.tei
dictionaries/stardict/wikdict-pl-el: dictionaries/tei/pol-ell.tei
dictionaries/kobo/dicthtml-pl-en.zip: dictionaries/tei/pol-eng.tei
dictionaries/stardict/wikdict-pl-en: dictionaries/tei/pol-eng.tei
dictionaries/kobo/dicthtml-pl-es.zip: dictionaries/tei/pol-spa.tei
dictionaries/stardict/wikdict-pl-es: dictionaries/tei/pol-spa.tei
dictionaries/kobo/dicthtml-pl-fi.zip: dictionaries/tei/pol-fin.tei
dictionaries/stardict/wikdict-pl-fi: dictionaries/tei/pol-fin.tei
dictionaries/kobo/dicthtml-pl-fr.zip: dictionaries/tei/pol-fra.tei
dictionaries/stardict/wikdict-pl-fr: dictionaries/tei/pol-fra.tei
dictionaries/kobo/dicthtml-pl-ga.zip: dictionaries/tei/pol-gle.tei
dictionaries/stardict/wikdict-pl-ga: dictionaries/tei/pol-gle.tei
dictionaries/kobo/dicthtml-pl-id.zip: dictionaries/tei/pol-ind.tei
dictionaries/stardict/wikdict-pl-id: dictionaries/tei/pol-ind.tei
dictionaries/kobo/dicthtml-pl-it.zip: dictionaries/tei/pol-ita.tei
dictionaries/stardict/wikdict-pl-it: dictionaries/tei/pol-ita.tei
dictionaries/kobo/dicthtml-pl-ja.zip: dictionaries/tei/pol-jpn.tei
dictionaries/stardict/wikdict-pl-ja: dictionaries/tei/pol-jpn.tei
dictionaries/kobo/dicthtml-pl-ku.zip: dictionaries/tei/pol-kur.tei
dictionaries/stardict/wikdict-pl-ku: dictionaries/tei/pol-kur.tei
dictionaries/kobo/dicthtml-pl-la.zip: dictionaries/tei/pol-lat.tei
dictionaries/stardict/wikdict-pl-la: dictionaries/tei/pol-lat.tei
dictionaries/kobo/dicthtml-pl-lt.zip: dictionaries/tei/pol-lit.tei
dictionaries/stardict/wikdict-pl-lt: dictionaries/tei/pol-lit.tei
dictionaries/kobo/dicthtml-pl-mg.zip: dictionaries/tei/pol-mlg.tei
dictionaries/stardict/wikdict-pl-mg: dictionaries/tei/pol-mlg.tei
dictionaries/kobo/dicthtml-pl-nl.zip: dictionaries/tei/pol-nld.tei
dictionaries/stardict/wikdict-pl-nl: dictionaries/tei/pol-nld.tei
dictionaries/kobo/dicthtml-pl-no.zip: dictionaries/tei/pol-nor.tei
dictionaries/stardict/wikdict-pl-no: dictionaries/tei/pol-nor.tei
dictionaries/kobo/dicthtml-pl-pt.zip: dictionaries/tei/pol-por.tei
dictionaries/stardict/wikdict-pl-pt: dictionaries/tei/pol-por.tei
dictionaries/kobo/dicthtml-pl-ru.zip: dictionaries/tei/pol-rus.tei
dictionaries/stardict/wikdict-pl-ru: dictionaries/tei/pol-rus.tei
dictionaries/kobo/dicthtml-pl-sv.zip: dictionaries/tei/pol-swe.tei
dictionaries/stardict/wikdict-pl-sv: dictionaries/tei/pol-swe.tei
dictionaries/kobo/dicthtml-pl-tr.zip: dictionaries/tei/pol-tur.tei
dictionaries/stardict/wikdict-pl-tr: dictionaries/tei/pol-tur.tei
dictionaries/kobo/dicthtml-pl-zh.zip: dictionaries/tei/pol-zho.tei
dictionaries/stardict/wikdict-pl-zh: dictionaries/tei/pol-zho.tei
dictionaries/kobo/dicthtml-pt-bg.zip: dictionaries/tei/por-bul.tei
dictionaries/stardict/wikdict-pt-bg: dictionaries/tei/por-bul.tei
dictionaries/kobo/dicthtml-pt-ca.zip: dictionaries/tei/por-cat.tei
dictionaries/stardict/wikdict-pt-ca: dictionaries/tei/por-cat.tei
dictionaries/kobo/dicthtml-pt-de.zip: dictionaries/tei/por-deu.tei
dictionaries/stardict/wikdict-pt-de: dictionaries/tei/por-deu.tei
dictionaries/kobo/dicthtml-pt-el.zip: dictionaries/tei/por-ell.tei
dictionaries/stardict/wikdict-pt-el: dictionaries/tei/por-ell.tei
dictionaries/kobo/dicthtml-pt-en.zip: dictionaries/tei/por-eng.tei
dictionaries/stardict/wikdict-pt-en: dictionaries/tei/por-eng.tei
dictionaries/kobo/dicthtml-pt-es.zip: dictionaries/tei/por-spa.tei
dictionaries/stardict/wikdict-pt-es: dictionaries/tei/por-spa.tei
dictionaries/kobo/dicthtml-pt-fi.zip: dictionaries/tei/por-fin.tei
dictionaries/stardict/wikdict-pt-fi: dictionaries/tei/por-fin.tei
dictionaries/kobo/dicthtml-pt-fr.zip: dictionaries/tei/por-fra.tei
dictionaries/stardict/wikdict-pt-fr: dictionaries/tei/por-fra.tei
dictionaries/kobo/dicthtml-pt-ga.zip: dictionaries/tei/por-gle.tei
dictionaries/stardict/wikdict-pt-ga: dictionaries/tei/por-gle.tei
dictionaries/kobo/dicthtml-pt-id.zip: dictionaries/tei/por-ind.tei
dictionaries/stardict/wikdict-pt-id: dictionaries/tei/por-ind.tei
dictionaries/kobo/dicthtml-pt-it.zip: dictionaries/tei/por-ita.tei
dictionaries/stardict/wikdict-pt-it: dictionaries/tei/por-ita.tei
dictionaries/kobo/dicthtml-pt-ja.zip: dictionaries/tei/por-jpn.tei
dictionaries/stardict/wikdict-pt-ja: dictionaries/tei/por-jpn.tei
dictionaries/kobo/dicthtml-pt-ku.zip: dictionaries/tei/por-kur.tei
dictionaries/stardict/wikdict-pt-ku: dictionaries/tei/por-kur.tei
dictionaries/kobo/dicthtml-pt-la.zip: dictionaries/tei/por-lat.tei
dictionaries/stardict/wikdict-pt-la: dictionaries/tei/por-lat.tei
dictionaries/kobo/dicthtml-pt-lt.zip: dictionaries/tei/por-lit.tei
dictionaries/stardict/wikdict-pt-lt: dictionaries/tei/por-lit.tei
dictionaries/kobo/dicthtml-pt-mg.zip: dictionaries/tei/por-mlg.tei
dictionaries/stardict/wikdict-pt-mg: dictionaries/tei/por-mlg.tei
dictionaries/kobo/dicthtml-pt-nl.zip: dictionaries/tei/por-nld.tei
dictionaries/stardict/wikdict-pt-nl: dictionaries/tei/por-nld.tei
dictionaries/kobo/dicthtml-pt-no.zip: dictionaries/tei/por-nor.tei
dictionaries/stardict/wikdict-pt-no: dictionaries/tei/por-nor.tei
dictionaries/kobo/dicthtml-pt-pl.zip: dictionaries/tei/por-pol.tei
dictionaries/stardict/wikdict-pt-pl: dictionaries/tei/por-pol.tei
dictionaries/kobo/dicthtml-pt-ru.zip: dictionaries/tei/por-rus.tei
dictionaries/stardict/wikdict-pt-ru: dictionaries/tei/por-rus.tei
dictionaries/kobo/dicthtml-pt-sv.zip: dictionaries/tei/por-swe.tei
dictionaries/stardict/wikdict-pt-sv: dictionaries/tei/por-swe.tei
dictionaries/kobo/dicthtml-pt-tr.zip: dictionaries/tei/por-tur.tei
dictionaries/stardict/wikdict-pt-tr: dictionaries/tei/por-tur.tei
dictionaries/kobo/dicthtml-pt-zh.zip: dictionaries/tei/por-zho.tei
dictionaries/stardict/wikdict-pt-zh: dictionaries/tei/por-zho.tei
dictionaries/kobo/dicthtml-ru-bg.zip: dictionaries/tei/rus-bul.tei
dictionaries/stardict/wikdict-ru-bg: dictionaries/tei/rus-bul.tei
dictionaries/kobo/dicthtml-ru-ca.zip: dictionaries/tei/rus-cat.tei
dictionaries/stardict/wikdict-ru-ca: dictionaries/tei/rus-cat.tei
dictionaries/kobo/dicthtml-ru-de.zip: dictionaries/tei/rus-deu.tei
dictionaries/stardict/wikdict-ru-de: dictionaries/tei/rus-deu.tei
dictionaries/kobo/dicthtml-ru-el.zip: dictionaries/tei/rus-ell.tei
dictionaries/stardict/wikdict-ru-el: dictionaries/tei/rus-ell.tei
dictionaries/kobo/dicthtml-ru-en.zip: dictionaries/tei/rus-eng.tei
dictionaries/stardict/wikdict-ru-en: dictionaries/tei/rus-eng.tei
dictionaries/kobo/dicthtml-ru-es.zip: dictionaries/tei/rus-spa.tei
dictionaries/stardict/wikdict-ru-es: dictionaries/tei/rus-spa.tei
dictionaries/kobo/dicthtml-ru-fi.zip: dictionaries/tei/rus-fin.tei
dictionaries/stardict/wikdict-ru-fi: dictionaries/tei/rus-fin.tei
dictionaries/kobo/dicthtml-ru-fr.zip: dictionaries/tei/rus-fra.tei
dictionaries/stardict/wikdict-ru-fr: dictionaries/tei/rus-fra.tei
dictionaries/kobo/dicthtml-ru-ga.zip: dictionaries/tei/rus-gle.tei
dictionaries/stardict/wikdict-ru-ga: dictionaries/tei/rus-gle.tei
dictionaries/kobo/dicthtml-ru-id.zip: dictionaries/tei/rus-ind.tei
dictionaries/stardict/wikdict-ru-id: dictionaries/tei/rus-ind.tei
dictionaries/kobo/dicthtml-ru-it.zip: dictionaries/tei/rus-ita.tei
dictionaries/stardict/wikdict-ru-it: dictionaries/tei/rus-ita.tei
dictionaries/kobo/dicthtml-ru-ja.zip: dictionaries/tei/rus-jpn.tei
dictionaries/stardict/wikdict-ru-ja: dictionaries/tei/rus-jpn.tei
dictionaries/kobo/dicthtml-ru-ku.zip: dictionaries/tei/rus-kur.tei
dictionaries/stardict/wikdict-ru-ku: dictionaries/tei/rus-kur.tei
dictionaries/kobo/dicthtml-ru-la.zip: dictionaries/tei/rus-lat.tei
dictionaries/stardict/wikdict-ru-la: dictionaries/tei/rus-lat.tei
dictionaries/kobo/dicthtml-ru-lt.zip: dictionaries/tei/rus-lit.tei
dictionaries/stardict/wikdict-ru-lt: dictionaries/tei/rus-lit.tei
dictionaries/kobo/dicthtml-ru-mg.zip: dictionaries/tei/rus-mlg.tei
dictionaries/stardict/wikdict-ru-mg: dictionaries/tei/rus-mlg.tei
dictionaries/kobo/dicthtml-ru-nl.zip: dictionaries/tei/rus-nld.tei
dictionaries/stardict/wikdict-ru-nl: dictionaries/tei/rus-nld.tei
dictionaries/kobo/dicthtml-ru-no.zip: dictionaries/tei/rus-nor.tei
dictionaries/stardict/wikdict-ru-no: dictionaries/tei/rus-nor.tei
dictionaries/kobo/dicthtml-ru-pl.zip: dictionaries/tei/rus-pol.tei
dictionaries/stardict/wikdict-ru-pl: dictionaries/tei/rus-pol.tei
dictionaries/kobo/dicthtml-ru-pt.zip: dictionaries/tei/rus-por.tei
dictionaries/stardict/wikdict-ru-pt: dictionaries/tei/rus-por.tei
dictionaries/kobo/dicthtml-ru-sv.zip: dictionaries/tei/rus-swe.tei
dictionaries/stardict/wikdict-ru-sv: dictionaries/tei/rus-swe.tei
dictionaries/kobo/dicthtml-ru-tr.zip: dictionaries/tei/rus-tur.tei
dictionaries/stardict/wikdict-ru-tr: dictionaries/tei/rus-tur.tei
dictionaries/kobo/dicthtml-ru-zh.zip: dictionaries/tei/rus-zho.tei
dictionaries/stardict/wikdict-ru-zh: dictionaries/tei/rus-zho.tei
dictionaries/kobo/dicthtml-sv-bg.zip: dictionaries/tei/swe-bul.tei
dictionaries/stardict/wikdict-sv-bg: dictionaries/tei/swe-bul.tei
dictionaries/kobo/dicthtml-sv-ca.zip: dictionaries/tei/swe-cat.tei
dictionaries/stardict/wikdict-sv-ca: dictionaries/tei/swe-cat.tei
dictionaries/kobo/dicthtml-sv-de.zip: dictionaries/tei/swe-deu.tei
dictionaries/stardict/wikdict-sv-de: dictionaries/tei/swe-deu.tei
dictionaries/kobo/dicthtml-sv-el.zip: dictionaries/tei/swe-ell.tei
dictionaries/stardict/wikdict-sv-el: dictionaries/tei/swe-ell.tei
dictionaries/kobo/dicthtml-sv-en.zip: dictionaries/tei/swe-eng.tei
dictionaries/stardict/wikdict-sv-en: dictionaries/tei/swe-eng.tei
dictionaries/kobo/dicthtml-sv-es.zip: dictionaries/tei/swe-spa.tei
dictionaries/stardict/wikdict-sv-es: dictionaries/tei/swe-spa.tei
dictionaries/kobo/dicthtml-sv-fi.zip: dictionaries/tei/swe-fin.tei
dictionaries/stardict/wikdict-sv-fi: dictionaries/tei/swe-fin.tei
dictionaries/kobo/dicthtml-sv-fr.zip: dictionaries/tei/swe-fra.tei
dictionaries/stardict/wikdict-sv-fr: dictionaries/tei/swe-fra.tei
dictionaries/kobo/dicthtml-sv-ga.zip: dictionaries/tei/swe-gle.tei
dictionaries/stardict/wikdict-sv-ga: dictionaries/tei/swe-gle.tei
dictionaries/kobo/dicthtml-sv-id.zip: dictionaries/tei/swe-ind.tei
dictionaries/stardict/wikdict-sv-id: dictionaries/tei/swe-ind.tei
dictionaries/kobo/dicthtml-sv-it.zip: dictionaries/tei/swe-ita.tei
dictionaries/stardict/wikdict-sv-it: dictionaries/tei/swe-ita.tei
dictionaries/kobo/dicthtml-sv-ja.zip: dictionaries/tei/swe-jpn.tei
dictionaries/stardict/wikdict-sv-ja: dictionaries/tei/swe-jpn.tei
dictionaries/kobo/dicthtml-sv-ku.zip: dictionaries/tei/swe-kur.tei
dictionaries/stardict/wikdict-sv-ku: dictionaries/tei/swe-kur.tei
dictionaries/kobo/dicthtml-sv-la.zip: dictionaries/tei/swe-lat.tei
dictionaries/stardict/wikdict-sv-la: dictionaries/tei/swe-lat.tei
dictionaries/kobo/dicthtml-sv-lt.zip: dictionaries/tei/swe-lit.tei
dictionaries/stardict/wikdict-sv-lt: dictionaries/tei/swe-lit.tei
dictionaries/kobo/dicthtml-sv-mg.zip: dictionaries/tei/swe-mlg.tei
dictionaries/stardict/wikdict-sv-mg: dictionaries/tei/swe-mlg.tei
dictionaries/kobo/dicthtml-sv-nl.zip: dictionaries/tei/swe-nld.tei
dictionaries/stardict/wikdict-sv-nl: dictionaries/tei/swe-nld.tei
dictionaries/kobo/dicthtml-sv-no.zip: dictionaries/tei/swe-nor.tei
dictionaries/stardict/wikdict-sv-no: dictionaries/tei/swe-nor.tei
dictionaries/kobo/dicthtml-sv-pl.zip: dictionaries/tei/swe-pol.tei
dictionaries/stardict/wikdict-sv-pl: dictionaries/tei/swe-pol.tei
dictionaries/kobo/dicthtml-sv-pt.zip: dictionaries/tei/swe-por.tei
dictionaries/stardict/wikdict-sv-pt: dictionaries/tei/swe-por.tei
dictionaries/kobo/dicthtml-sv-ru.zip: dictionaries/tei/swe-rus.tei
dictionaries/stardict/wikdict-sv-ru: dictionaries/tei/swe-rus.tei
dictionaries/kobo/dicthtml-sv-tr.zip: dictionaries/tei/swe-tur.tei
dictionaries/stardict/wikdict-sv-tr: dictionaries/tei/swe-tur.tei
dictionaries/kobo/dicthtml-sv-zh.zip: dictionaries/tei/swe-zho.tei
dictionaries/stardict/wikdict-sv-zh: dictionaries/tei/swe-zho.tei
dictionaries/kobo/dicthtml-tr-bg.zip: dictionaries/tei/tur-bul.tei
dictionaries/stardict/wikdict-tr-bg: dictionaries/tei/tur-bul.tei
dictionaries/kobo/dicthtml-tr-ca.zip: dictionaries/tei/tur-cat.tei
dictionaries/stardict/wikdict-tr-ca: dictionaries/tei/tur-cat.tei
dictionaries/kobo/dicthtml-tr-de.zip: dictionaries/tei/tur-deu.tei
dictionaries/stardict/wikdict-tr-de: dictionaries/tei/tur-deu.tei
dictionaries/kobo/dicthtml-tr-el.zip: dictionaries/tei/tur-ell.tei
dictionaries/stardict/wikdict-tr-el: dictionaries/tei/tur-ell.tei
dictionaries/kobo/dicthtml-tr-en.zip: dictionaries/tei/tur-eng.tei
dictionaries/stardict/wikdict-tr-en: dictionaries/tei/tur-eng.tei
dictionaries/kobo/dicthtml-tr-es.zip: dictionaries/tei/tur-spa.tei
dictionaries/stardict/wikdict-tr-es: dictionaries/tei/tur-spa.tei
dictionaries/kobo/dicthtml-tr-fi.zip: dictionaries/tei/tur-fin.tei
dictionaries/stardict/wikdict-tr-fi: dictionaries/tei/tur-fin.tei
dictionaries/kobo/dicthtml-tr-fr.zip: dictionaries/tei/tur-fra.tei
dictionaries/stardict/wikdict-tr-fr: dictionaries/tei/tur-fra.tei
dictionaries/kobo/dicthtml-tr-ga.zip: dictionaries/tei/tur-gle.tei
dictionaries/stardict/wikdict-tr-ga: dictionaries/tei/tur-gle.tei
dictionaries/kobo/dicthtml-tr-id.zip: dictionaries/tei/tur-ind.tei
dictionaries/stardict/wikdict-tr-id: dictionaries/tei/tur-ind.tei
dictionaries/kobo/dicthtml-tr-it.zip: dictionaries/tei/tur-ita.tei
dictionaries/stardict/wikdict-tr-it: dictionaries/tei/tur-ita.tei
dictionaries/kobo/dicthtml-tr-ja.zip: dictionaries/tei/tur-jpn.tei
dictionaries/stardict/wikdict-tr-ja: dictionaries/tei/tur-jpn.tei
dictionaries/kobo/dicthtml-tr-ku.zip: dictionaries/tei/tur-kur.tei
dictionaries/stardict/wikdict-tr-ku: dictionaries/tei/tur-kur.tei
dictionaries/kobo/dicthtml-tr-la.zip: dictionaries/tei/tur-lat.tei
dictionaries/stardict/wikdict-tr-la: dictionaries/tei/tur-lat.tei
dictionaries/kobo/dicthtml-tr-lt.zip: dictionaries/tei/tur-lit.tei
dictionaries/stardict/wikdict-tr-lt: dictionaries/tei/tur-lit.tei
dictionaries/kobo/dicthtml-tr-mg.zip: dictionaries/tei/tur-mlg.tei
dictionaries/stardict/wikdict-tr-mg: dictionaries/tei/tur-mlg.tei
dictionaries/kobo/dicthtml-tr-nl.zip: dictionaries/tei/tur-nld.tei
dictionaries/stardict/wikdict-tr-nl: dictionaries/tei/tur-nld.tei
dictionaries/kobo/dicthtml-tr-no.zip: dictionaries/tei/tur-nor.tei
dictionaries/stardict/wikdict-tr-no: dictionaries/tei/tur-nor.tei
dictionaries/kobo/dicthtml-tr-pl.zip: dictionaries/tei/tur-pol.tei
dictionaries/stardict/wikdict-tr-pl: dictionaries/tei/tur-pol.tei
dictionaries/kobo/dicthtml-tr-pt.zip: dictionaries/tei/tur-por.tei
dictionaries/stardict/wikdict-tr-pt: dictionaries/tei/tur-por.tei
dictionaries/kobo/dicthtml-tr-ru.zip: dictionaries/tei/tur-rus.tei
dictionaries/stardict/wikdict-tr-ru: dictionaries/tei/tur-rus.tei
dictionaries/kobo/dicthtml-tr-sv.zip: dictionaries/tei/tur-swe.tei
dictionaries/stardict/wikdict-tr-sv: dictionaries/tei/tur-swe.tei
dictionaries/kobo/dicthtml-tr-zh.zip: dictionaries/tei/tur-zho.tei
dictionaries/stardict/wikdict-tr-zh: dictionaries/tei/tur-zho.tei
dictionaries/kobo/dicthtml-zh-bg.zip: dictionaries/tei/zho-bul.tei
dictionaries/stardict/wikdict-zh-bg: dictionaries/tei/zho-bul.tei
dictionaries/kobo/dicthtml-zh-ca.zip: dictionaries/tei/zho-cat.tei
dictionaries/stardict/wikdict-zh-ca: dictionaries/tei/zho-cat.tei
dictionaries/kobo/dicthtml-zh-de.zip: dictionaries/tei/zho-deu.tei
dictionaries/stardict/wikdict-zh-de: dictionaries/tei/zho-deu.tei
dictionaries/kobo/dicthtml-zh-el.zip: dictionaries/tei/zho-ell.tei
dictionaries/stardict/wikdict-zh-el: dictionaries/tei/zho-ell.tei
dictionaries/kobo/dicthtml-zh-en.zip: dictionaries/tei/zho-eng.tei
dictionaries/stardict/wikdict-zh-en: dictionaries/tei/zho-eng.tei
dictionaries/kobo/dicthtml-zh-es.zip: dictionaries/tei/zho-spa.tei
dictionaries/stardict/wikdict-zh-es: dictionaries/tei/zho-spa.tei
dictionaries/kobo/dicthtml-zh-fi.zip: dictionaries/tei/zho-fin.tei
dictionaries/stardict/wikdict-zh-fi: dictionaries/tei/zho-fin.tei
dictionaries/kobo/dicthtml-zh-fr.zip: dictionaries/tei/zho-fra.tei
dictionaries/stardict/wikdict-zh-fr: dictionaries/tei/zho-fra.tei
dictionaries/kobo/dicthtml-zh-ga.zip: dictionaries/tei/zho-gle.tei
dictionaries/stardict/wikdict-zh-ga: dictionaries/tei/zho-gle.tei
dictionaries/kobo/dicthtml-zh-id.zip: dictionaries/tei/zho-ind.tei
dictionaries/stardict/wikdict-zh-id: dictionaries/tei/zho-ind.tei
dictionaries/kobo/dicthtml-zh-it.zip: dictionaries/tei/zho-ita.tei
dictionaries/stardict/wikdict-zh-it: dictionaries/tei/zho-ita.tei
dictionaries/kobo/dicthtml-zh-ja.zip: dictionaries/tei/zho-jpn.tei
dictionaries/stardict/wikdict-zh-ja: dictionaries/tei/zho-jpn.tei
dictionaries/kobo/dicthtml-zh-ku.zip: dictionaries/tei/zho-kur.tei
dictionaries/stardict/wikdict-zh-ku: dictionaries/tei/zho-kur.tei
dictionaries/kobo/dicthtml-zh-la.zip: dictionaries/tei/zho-lat.tei
dictionaries/stardict/wikdict-zh-la: dictionaries/tei/zho-lat.tei
dictionaries/kobo/dicthtml-zh-lt.zip: dictionaries/tei/zho-lit.tei
dictionaries/stardict/wikdict-zh-lt: dictionaries/tei/zho-lit.tei
dictionaries/kobo/dicthtml-zh-mg.zip: dictionaries/tei/zho-mlg.tei
dictionaries/stardict/wikdict-zh-mg: dictionaries/tei/zho-mlg.tei
dictionaries/kobo/dicthtml-zh-nl.zip: dictionaries/tei/zho-nld.tei
dictionaries/stardict/wikdict-zh-nl: dictionaries/tei/zho-nld.tei
dictionaries/kobo/dicthtml-zh-no.zip: dictionaries/tei/zho-nor.tei
dictionaries/stardict/wikdict-zh-no: dictionaries/tei/zho-nor.tei
dictionaries/kobo/dicthtml-zh-pl.zip: dictionaries/tei/zho-pol.tei
dictionaries/stardict/wikdict-zh-pl: dictionaries/tei/zho-pol.tei
dictionaries/kobo/dicthtml-zh-pt.zip: dictionaries/tei/zho-por.tei
dictionaries/stardict/wikdict-zh-pt: dictionaries/tei/zho-por.tei
dictionaries/kobo/dicthtml-zh-ru.zip: dictionaries/tei/zho-rus.tei
dictionaries/stardict/wikdict-zh-ru: dictionaries/tei/zho-rus.tei
dictionaries/kobo/dicthtml-zh-sv.zip: dictionaries/tei/zho-swe.tei
dictionaries/stardict/wikdict-zh-sv: dictionaries/tei/zho-swe.tei
dictionaries/kobo/dicthtml-zh-tr.zip: dictionaries/tei/zho-tur.tei
dictionaries/stardict/wikdict-zh-tr: dictionaries/tei/zho-tur.tei
