import os
import sys
import glob
from itertools import permutations
import sqlite3

from languages import language_codes3, language_names

supported_langs = [
    "bg",
    "ca",
    "cs",
    "de",
    "da",
    "el",
    "en",
    "es",
    "fi",
    "fr",
    "ga",
    "id",
    "it",
    "ja",
    "ku",
    "la",
    "lt",
    "mg",
    "nl",
    "no",
    "pl",
    "pt",
    "ru",
    "sv",
    "tr",
    "zh",
]


def make_for_langs(functions, langs, **kwargs):
    """Executes functions for all given languages

    `langs` can also be "all" to execute on all supported languages.
    """
    if langs == ["all"]:
        langs = supported_langs
    for lang in langs:
        for func in functions:
            print(lang, func.__name__)
            func(lang)


def make_for_lang_permutations(functions, langs, **kwargs):
    """Executes functions for all pairwise combinations of the given langs.

    `langs` can also be "all" to execute on all supported languages.
    """
    if langs == ["all"]:
        langs = supported_langs
    assert len(langs) >= 2, "Need at least two languages"

    for func in functions:
        print(">> " + func.__name__)
        for from_lang, to_lang in permutations(langs, 2):
            print(from_lang, to_lang)
            func(from_lang, to_lang)


def make_targets(
    lang, out_path, targets, in_path=None, only=None, sql=None, attach=(), vacuum=True
):
    if out_path.endswith(".sqlite3"):
        conn = sqlite3.connect("dictionaries/%s" % out_path)
    else:
        os.makedirs("dictionaries/" + out_path, exist_ok=True)
        conn = sqlite3.connect("dictionaries/%s/%s.sqlite3" % (out_path, lang))

    # Enable loading SQLite extensions (needed for spellfix1)
    conn.enable_load_extension(True)

    try:
        conn.execute(
            "ATTACH DATABASE 'dictionaries/%s/%s.sqlite3' AS %s"
            % (in_path, lang, in_path)
        )
    except sqlite3.dbapi2.OperationalError:
        print("Error attaching ", in_path, lang, "database")
        raise

    for a in attach:
        conn.execute("ATTACH DATABASE " + a)
        if "wdweb/wikdict.sqlite3" in a:
            # Avoid errors when running multiple processes in parallel. Must be
            # enabled before tx starts.
            conn.execute("PRAGMA wikdict.journal_mode=WAL")

    if sql:
        cur = conn.cursor()
        cur.execute(sql)
        from tabulate import tabulate

        print(tabulate(cur, [col[0] for col in cur.description]))
        return

    print("%s/%s:" % (out_path, lang), flush=True, end=" ")
    for name, f in targets:
        if not only or only == name:
            print(name, flush=True, end=" ")
            f(conn, lang)
    conn.commit()
    if not only and vacuum:
        # conn.isolation_level = None
        # print("vacuum", flush=True, end=" ")
        # conn.execute("VACUUM main")
        print("analyze", flush=True, end=" ")
        conn.execute("ANALYZE main")
    print()


def koreader_dict_list():
    """Generate KOReader's downloadable-dictionary list for all built StarDict
    dictionaries, as a self-contained Lua module printed to stdout.

    The module returns a table of dictionary entries. It is meant to be saved
    as KOReader's `frontend/ui/data/dictionaries_wikdict.lua` and merged into
    `dictionaries.lua` with:

        for _, d in ipairs(require("ui/data/dictionaries_wikdict")) do
            table.insert(dictionaries, d)
        end

    Iterates the StarDict dirs that actually exist (so only pairs with a
    published zip are listed) and reads the headword count from each `.ifo`.
    """
    base_url = "https://download.wikdict.com/dictionaries/stardict"
    entries = []
    for ifo in sorted(glob.glob("dictionaries/stardict/wikdict-*/stardict.ifo")):
        pair = os.path.basename(os.path.dirname(ifo))  # e.g. "wikdict-de-en"
        from_lang, to_lang = pair[len("wikdict-") :].split("-")

        wordcount = None
        with open(ifo, encoding="utf-8") as f:
            for line in f:
                if line.startswith("wordcount="):
                    wordcount = int(line.split("=", 1)[1].strip())
                    break

        entries.append(
            {
                "name": "%s-%s (WikDict)"
                % (language_names[from_lang], language_names[to_lang]),
                "lang_in": language_codes3[from_lang],
                "lang_out": language_codes3[to_lang],
                "entries": wordcount,
                "url": "%s/%s.zip" % (base_url, pair),
            }
        )

    entries.sort(key=lambda e: e["name"])

    print("-- WikDict bilingual dictionaries for KOReader.")
    print("-- Generated by wikdict-gen: `python3 src/helper.py koreader`. Do not edit by hand.")
    print("-- Source: WikDict (Wiktionary via DBnary, https://www.wikdict.com).")
    print("-- License: CC BY-SA 3.0.")
    print("return {")
    for e in entries:
        print("    {")
        print('        name = "%s",' % e["name"])
        print('        lang_in = "%s",' % e["lang_in"])
        print('        lang_out = "%s",' % e["lang_out"])
        print("        entries = %d," % e["entries"])
        print('        license = "CC BY-SA 3.0",')
        print('        url = "%s",' % e["url"])
        print("    },")
    print("}")


if __name__ == "__main__":
    if sys.argv[1] == "all_pairs":
        print(
            " ".join(
                from_lang + "-" + to_lang
                for from_lang, to_lang in permutations(supported_langs, 2)
            )
        )
    elif sys.argv[1] == "all_langs":
        print(" ".join(supported_langs))
    elif sys.argv[1] == "koreader":
        koreader_dict_list()
    elif sys.argv[1] == "makefile":
        for from_lang, to_lang in permutations(supported_langs, 2):
            print(
                "dictionaries/kobo/dicthtml-{}.zip: dictionaries/tei/{}.tei".format(
                    from_lang + "-" + to_lang,
                    language_codes3[from_lang] + "-" + language_codes3[to_lang],
                )
            )
            print(
                "dictionaries/stardict/wikdict-{}: dictionaries/tei/{}.tei".format(
                    from_lang + "-" + to_lang,
                    language_codes3[from_lang] + "-" + language_codes3[to_lang],
                )
            )
    else:
        print("Unknwn command %s" % sys.argv[1])
